const draftProspects = [
  {
    "rank": 1,
    "ordemCsv": "05e",
    "slug": "darryn-peterson",
    "nome": "Darryn Peterson",
    "status": "",
    "alcance": "1-1",
    "bio": "Escolta | Kansas (EUA) | 1.95m | 6'5 | 19 anos",
    "posicao": "Escolta",
    "time": "Kansas (EUA)",
    "altura": "1.95m",
    "alturaImperial": "6'5",
    "idade": "19 anos",
    "arquetipoOfensivo": "Gerador de ataque nos três níveis.",
    "arquetipoDefensivo": "Parador nas rotações e positivo no ponto de ataque.",
    "motivoEscolha": "É o melhor projeto do seu arquétipo em 20 anos.",
    "chaveDesenvolvimento": "",
    "tetoPiso": "60/40",
    "espelho": "Shai Gilgeous-Alexander",
    "foto": "img/draft/Darryn-Peterson.png",
    "updatedAt": "2026-01-05T01:08:29Z",
    "id": "aac469ba-7573-463a-9819-e72cdeacfc82"
  },
  {
    "rank": 2,
    "ordemCsv": "05g",
    "slug": "cam-boozer",
    "nome": "Cam Boozer",
    "status": "",
    "alcance": "2-4",
    "bio": "Grande | Duke (EUA) | 2.06m | 6'9 | 18 anos",
    "posicao": "Grande",
    "time": "Duke (EUA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "18 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "50/50",
    "espelho": "Kevin Love moderno",
    "foto": "img/draft/Cam-Boozer.png",
    "updatedAt": "2026-01-05T01:10:33Z",
    "id": "c110c82a-2f8d-44dd-ac7b-44d862808e82"
  },
  {
    "rank": 3,
    "ordemCsv": "05h",
    "slug": "caleb-wilson",
    "nome": "Caleb Wilson",
    "status": "",
    "alcance": "2-6",
    "bio": "Ala | North Carolina (EUA) | 2.08m | 6'10 | 19 anos",
    "posicao": "Ala",
    "time": "North Carolina (EUA)",
    "altura": "2.08m",
    "alturaImperial": "6'10",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "60/40",
    "espelho": "Kevin Garnett",
    "foto": "img/draft/Caleb-Wilson.png",
    "updatedAt": "2026-01-05T01:10:51Z",
    "id": "833cc494-40dd-43a7-b0fa-2606b1e6ee8b"
  },
  {
    "rank": 4,
    "ordemCsv": "05h8",
    "slug": "aj-dybansta",
    "nome": "AJ Dybansta",
    "status": "",
    "alcance": "2-6",
    "bio": "Ala | BYU (EUA) | 2.06m | 6'9 | 19 anos",
    "posicao": "Ala",
    "time": "BYU (EUA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "70/30",
    "espelho": "Rudy Gay dos sonhos",
    "foto": "img/draft/AJ-Dybansta.png",
    "updatedAt": "2026-01-05T01:10:53Z",
    "id": "2cb3dfc7-f033-4caf-ba64-138c20963881"
  },
  {
    "rank": 5,
    "ordemCsv": "05i",
    "slug": "labaron-philon",
    "nome": "Labaron Philon",
    "status": "SCOUT",
    "alcance": "3-7",
    "bio": "Armador |  Alabama (EUA) | 1.93m | 6'4 | 20 anos",
    "posicao": "Armador",
    "time": "Alabama (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "20 anos",
    "arquetipoOfensivo": "Iniciador e finalizador de jogadas.",
    "arquetipoDefensivo": "Parador no PdA no perímetro.",
    "motivoEscolha": "Ritmo único no Pick e caráter 2-Way como armador.",
    "chaveDesenvolvimento": "Fisicalidade no Drive e mais repetições jogando o X1 sem Pick.",
    "tetoPiso": "50/50",
    "espelho": "Jrue Holiday + Darius Garland",
    "foto": "img/draft/Labaron-Philon.png",
    "updatedAt": "2026-02-19T14:38:53Z",
    "id": "93345ec3-892a-4ff4-92fa-4e39c47ad0da"
  },
  {
    "rank": 6,
    "ordemCsv": "05l",
    "slug": "darius-acuff-jr",
    "nome": "Darius Acuff Jr",
    "status": "SCOUT",
    "alcance": "5-10",
    "bio": "Armador | Arkansas (EUA) | 1.88m | 6'3 | 19 anos",
    "posicao": "Armador",
    "time": "Arkansas (EUA)",
    "altura": "1.88m",
    "alturaImperial": "6'3",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "50/50",
    "espelho": "Kyle Lowry mais explosivo",
    "foto": "img/draft/Darius-Acuff-Jr.png",
    "updatedAt": "2026-02-19T14:38:52Z",
    "id": "f4a1db13-7620-424d-91e5-01e0877ee41f"
  },
  {
    "rank": 7,
    "ordemCsv": "05l8",
    "slug": "jayden-quaintance",
    "nome": "Jayden Quaintance",
    "status": "",
    "alcance": "5-10",
    "bio": "Grande | Kentucky (EUA) | 2.06m | 6'9 | 18 anos",
    "posicao": "Grande",
    "time": "Kentucky (EUA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "18 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "60/40",
    "espelho": "Ben Wallace",
    "foto": "img/draft/Jayden-Quaintance.png",
    "updatedAt": "2026-01-05T01:11:05Z",
    "id": "b8eeb704-a51c-435e-85fc-69a6df1c28b7"
  },
  {
    "rank": 8,
    "ordemCsv": "05m",
    "slug": "mikel-brown-jr",
    "nome": "Mikel Brown Jr",
    "status": "",
    "alcance": "4-10",
    "bio": "Armador | Louisville (EUA) | 1.90m | 6'3 | 20 anos",
    "posicao": "Armador",
    "time": "Louisville (EUA)",
    "altura": "1.90m",
    "alturaImperial": "6'3",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "70/30",
    "espelho": "Tyrese Haliburton",
    "foto": "img/draft/Mikel-Brown-Jr.png",
    "updatedAt": "2026-01-05T01:11:09Z",
    "id": "0ac659f3-0972-4478-b74a-a75d15d19c2e"
  },
  {
    "rank": 9,
    "ordemCsv": "05r",
    "slug": "kingston-flemings",
    "nome": "Kingston Flemings",
    "status": "",
    "alcance": "7-10",
    "bio": "Armador | Houston (EUA) | 1.93m | 6'4 | 19 anos",
    "posicao": "Armador",
    "time": "Houston (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "60/40",
    "espelho": "",
    "foto": "img/draft/Kingston-Flemings.png",
    "updatedAt": "2026-01-05T01:11:13Z",
    "id": "0f9496c0-2f41-4422-b22d-40c7448b6d3f"
  },
  {
    "rank": 10,
    "ordemCsv": "05u",
    "slug": "karim-lopez",
    "nome": "Karim Lopez",
    "status": "",
    "alcance": "7-14",
    "bio": "Ala | NZ Breakers (AUS) | 2.03m | 6'8 | 19 anos",
    "posicao": "Ala",
    "time": "NZ Breakers (AUS)",
    "altura": "2.03m",
    "alturaImperial": "6'8",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "50/50",
    "espelho": "",
    "foto": "img/draft/Karim-Lopez.png",
    "updatedAt": "2026-01-05T01:11:15Z",
    "id": "8bf3f470-c9b4-43af-8555-a3ac55d9e17f"
  },
  {
    "rank": 11,
    "ordemCsv": "05u8",
    "slug": "cam-carr",
    "nome": "Cam Carr",
    "status": "",
    "alcance": "9-14",
    "bio": "Lateral | Baylor (EUA) | 1.96m | 6'6 | 21 anos",
    "posicao": "Lateral",
    "time": "Baylor (EUA)",
    "altura": "1.96m",
    "alturaImperial": "6'6",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "60/40",
    "espelho": "",
    "foto": "img/draft/Cam-Carr.png",
    "updatedAt": "2026-01-05T01:11:20Z",
    "id": "bf42bf81-3b53-40e3-80ad-d574bf49b0ac"
  },
  {
    "rank": 12,
    "ordemCsv": "05u9",
    "slug": "nate-ament",
    "nome": "Nate Ament",
    "status": "",
    "alcance": "5-18",
    "bio": "Ala | Tennessee (EUA) | 2.08m | 6'10 | 19 anos",
    "posicao": "Ala",
    "time": "Tennessee (EUA)",
    "altura": "2.08m",
    "alturaImperial": "6'10",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "90/10",
    "espelho": "Hedo Türkoğlu + Pascal Siakam",
    "foto": "img/draft/Nate-Ament.png",
    "updatedAt": "2026-01-05T01:11:24Z",
    "id": "9af1f13a-06f7-4158-af59-7db789759fdc"
  },
  {
    "rank": 13,
    "ordemCsv": "05ua",
    "slug": "koa-peat",
    "nome": "Koa Peat",
    "status": "",
    "alcance": "7-16",
    "bio": "Ala | Arizona (EUA) | 2.03m | 6'8 | 19 anos",
    "posicao": "Ala",
    "time": "Arizona (EUA)",
    "altura": "2.03m",
    "alturaImperial": "6'8",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "50/50",
    "espelho": "PJ Washington + Aaron Gordon",
    "foto": "img/draft/Koa-Peat.png",
    "updatedAt": "2026-01-05T01:11:29Z",
    "id": "951bf91e-8805-426e-863a-ef9604f9bb50"
  },
  {
    "rank": 14,
    "ordemCsv": "05uag",
    "slug": "christian-anderson",
    "nome": "Christian Anderson",
    "status": "",
    "alcance": "11-18",
    "bio": "Armador | Texas Tech (EUA) | 1.88m | 6'2 | 20 anos",
    "posicao": "Armador",
    "time": "Texas Tech (EUA)",
    "altura": "1.88m",
    "alturaImperial": "6'2",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "40/60",
    "espelho": "",
    "foto": "img/draft/Christian-Anderson.png",
    "updatedAt": "2026-01-05T01:11:33Z",
    "id": "6b85872e-0a95-44f0-a7bf-0d9d28b7a813"
  },
  {
    "rank": 15,
    "ordemCsv": "05uc",
    "slug": "amari-allen",
    "nome": "Amari Allen",
    "status": "SCOUT",
    "alcance": "11-20",
    "bio": "Ala | Alabama (EUA) | 2.03m | 6'8 | 20 anos",
    "posicao": "Ala",
    "time": "Alabama (EUA)",
    "altura": "2.03m",
    "alturaImperial": "6'8",
    "idade": "20 anos",
    "arquetipoOfensivo": "Conector e iniciador terciário",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2026-02-19T14:38:45Z",
    "id": "1cd97b21-cd81-4b08-93b9-cce240db021e"
  },
  {
    "rank": 16,
    "ordemCsv": "05ue",
    "slug": "aiden-sherell",
    "nome": "Aiden Sherell",
    "status": "SCOUT",
    "alcance": "",
    "bio": "Grande I Alabama (EUA) |",
    "posicao": "Grande I Alabama (EUA)",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2026-02-19T14:38:47Z",
    "id": "642cf679-c1ce-4298-b7c7-427936cd2585"
  },
  {
    "rank": 17,
    "ordemCsv": "05ueg",
    "slug": "billy-richmond",
    "nome": "Billy Richmond",
    "status": "SCOUT",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2026-02-19T14:38:47Z",
    "id": "bbdffa9d-9162-4382-9373-f6533ae8aa3a"
  },
  {
    "rank": 18,
    "ordemCsv": "05ug",
    "slug": "hannes-steinbach",
    "nome": "Hannes Steinbach",
    "status": "",
    "alcance": "12-20",
    "bio": "Grande | Washington (EUA) | 2.06m | 6'9 | 20 anos",
    "posicao": "Grande",
    "time": "Washington (EUA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Steven Adams que faz cesta",
    "foto": "img/draft/Hannes-Steinbach.png",
    "updatedAt": "2026-02-19T14:36:32Z",
    "id": "c17405d5-f1ac-4df9-a859-deae33071767"
  },
  {
    "rank": 19,
    "ordemCsv": "05v",
    "slug": "thomas-haugh",
    "nome": "Thomas Haugh",
    "status": "",
    "alcance": "",
    "bio": "Ala | Florida (EUA) | 2.06m | 6'9 | 22 anos",
    "posicao": "Ala",
    "time": "Florida (EUA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "22 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Jeff Green moderno",
    "foto": "img/draft/Thomas-Haugh.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "75cf8eb2-ccc6-4cc9-9fb2-f1016debe6b3"
  },
  {
    "rank": 20,
    "ordemCsv": "061",
    "slug": "tounde-yessoufou",
    "nome": "Tounde Yessoufou",
    "status": "",
    "alcance": "10-23",
    "bio": "Lateral | Baylor (EUA) | 1.96m | 6'5 | 20 anos",
    "posicao": "Lateral",
    "time": "Baylor (EUA)",
    "altura": "1.96m",
    "alturaImperial": "6'5",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Jaylen Brown",
    "foto": "img/draft/Tounde-Yessoufou.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "874b039b-f7e6-4a41-af6f-d3f5cc25915b"
  },
  {
    "rank": 21,
    "ordemCsv": "062",
    "slug": "isaiah-evans",
    "nome": "Isaiah Evans",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Duke (EUA) | 1.98m | 6'6 | 20 anos",
    "posicao": "Lateral",
    "time": "Duke (EUA)",
    "altura": "1.98m",
    "alturaImperial": "6'6",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Cam Reddish teórico",
    "foto": "img/draft/Isaiah-Evans.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "6aeec4fb-025f-4e5f-aff7-0690628664a6"
  },
  {
    "rank": 22,
    "ordemCsv": "06e",
    "slug": "dwayne-aristode",
    "nome": "Dwayne Aristode",
    "status": "",
    "alcance": "",
    "bio": "Ala | Arizona (EUA) | 2.04m | 6'8 | 19 anos",
    "posicao": "Ala",
    "time": "Arizona (EUA)",
    "altura": "2.04m",
    "alturaImperial": "6'8",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Nicolas Batum tunado",
    "foto": "img/draft/Dwayne-Aristode.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "80034535-ac80-4ca8-8a63-2781da537167"
  },
  {
    "rank": 23,
    "ordemCsv": "06eg",
    "slug": "neoklis-avdalas",
    "nome": "Neoklis Avdalas",
    "status": "",
    "alcance": "20-35",
    "bio": "Lateral | Virginia Tech (EUA) | 2.06m | 6'9 | 20 anos",
    "posicao": "Lateral",
    "time": "Virginia Tech (EUA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "60% do Luka Dončić",
    "foto": "img/draft/Neo-Avdalas.png",
    "updatedAt": "2026-02-19T14:36:40Z",
    "id": "e1835def-bfc4-47a4-a513-d4e435b4d86e"
  },
  {
    "rank": 24,
    "ordemCsv": "06f",
    "slug": "braylon-mullins",
    "nome": "Braylon Mullins",
    "status": "",
    "alcance": "",
    "bio": "Escolta | UConn (EUA) | 1.96m | 6'5 | 20 anos",
    "posicao": "Escolta",
    "time": "UConn (EUA)",
    "altura": "1.96m",
    "alturaImperial": "6'5",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Braylon-Mullins.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "9e0eded7-10da-4ba7-abd3-7cbf300f910b"
  },
  {
    "rank": 25,
    "ordemCsv": "06g",
    "slug": "dailyn-swain",
    "nome": "Dailyn Swain",
    "status": "",
    "alcance": "",
    "bio": "Ala | Texas (EUA) | 2.01m | 6'7 | 21 anos",
    "posicao": "Ala",
    "time": "Texas (EUA)",
    "altura": "2.01m",
    "alturaImperial": "6'7",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Jerami Grant que cria mais do que erra",
    "foto": "img/draft/Dailyn-Swain.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "9033f927-8408-4131-aa0f-b56908e59d91"
  },
  {
    "rank": 26,
    "ordemCsv": "06k",
    "slug": "braden-smith",
    "nome": "Braden Smith",
    "status": "",
    "alcance": "20-45",
    "bio": "Armador | Purdue (EUA) | 1.83m | 6'0 | 22 anos",
    "posicao": "Armador",
    "time": "Purdue (EUA)",
    "altura": "1.83m",
    "alturaImperial": "6'0",
    "idade": "22 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Mike Conley menor",
    "foto": "img/draft/Braden-Smith.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "6c49756e-7238-444c-8a0e-e62fb7617f05"
  },
  {
    "rank": 27,
    "ordemCsv": "06m",
    "slug": "henri-veesaar",
    "nome": "Henri Veesaar",
    "status": "",
    "alcance": "",
    "bio": "Grande | North Carolina (EUA) | 2.13m | 7'0 | 21 anos",
    "posicao": "Grande",
    "time": "North Carolina (EUA)",
    "altura": "2.13m",
    "alturaImperial": "7'0",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Moritz Wagner que não é soft",
    "foto": "img/draft/Henri-Veesaar.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "58b9e987-bd6c-487e-a7b8-3a8107901316"
  },
  {
    "rank": 28,
    "ordemCsv": "06v1o",
    "slug": "aday-mara",
    "nome": "Aday Mara",
    "status": "",
    "alcance": "",
    "bio": "Grande | Michigan (EUA) | 2.21m | 7'3 | 21 anos",
    "posicao": "Grande",
    "time": "Michigan (EUA)",
    "altura": "2.21m",
    "alturaImperial": "7'3",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Aday-Mara.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "3a4fd9bb-0310-46fb-91f0-32b90f29b572"
  },
  {
    "rank": 29,
    "ordemCsv": "06v1p",
    "slug": "dash-daniels",
    "nome": "Dash Daniels",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Melbourne (AUS) | 1.95m | 6'5 | 18 anos",
    "posicao": "Lateral",
    "time": "Melbourne (AUS)",
    "altura": "1.95m",
    "alturaImperial": "6'5",
    "idade": "18 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Dyson Daniels",
    "foto": "img/draft/Dash-Daniels.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "ea20fb5f-ef18-4c0c-9d33-55ba1bd81ec5"
  },
  {
    "rank": 30,
    "ordemCsv": "06v1pg",
    "slug": "nik-khamenia",
    "nome": "Nik Khamenia",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Duke (EUA) | 2.03m | 6'8 | 19 anos",
    "posicao": "Lateral",
    "time": "Duke (EUA)",
    "altura": "2.03m",
    "alturaImperial": "6'8",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Ni-Khamenia.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "2f272d2d-6238-4722-8288-7dc7d8129a8e"
  },
  {
    "rank": 31,
    "ordemCsv": "06v1po",
    "slug": "meleek-thomas",
    "nome": "Meleek Thomas",
    "status": "",
    "alcance": "",
    "bio": "Escolta | Arkansas (EUA) | 1.93m | 6'4 | 19 anos",
    "posicao": "Escolta",
    "time": "Arkansas (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Meleek-Thomas.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "e25fd71a-d729-4a55-b910-1dda55e7df39"
  },
  {
    "rank": 32,
    "ordemCsv": "06v1pq",
    "slug": "bennett-stirtz",
    "nome": "Bennett Stirtz",
    "status": "",
    "alcance": "",
    "bio": "Armador | Iowa (EUA) | 1.93m | 6'4 | 22 anos",
    "posicao": "Armador",
    "time": "Iowa (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "22 anos",
    "arquetipoOfensivo": "Criador completo no Pick e com chute pronto.",
    "arquetipoDefensivo": "Ajudante de sistema inteligente e ativo na linha de passe.",
    "motivoEscolha": "Motorzinho ofensivo com jogo refinado.",
    "chaveDesenvolvimento": "",
    "tetoPiso": "25/75",
    "espelho": "Ty Jerome",
    "foto": "img/draft/Bennett-Stirtz.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "e2bcbf0b-ee77-4576-b83d-1cdd5ae35aec"
  },
  {
    "rank": 33,
    "ordemCsv": "06v1q",
    "slug": "brayden-burries",
    "nome": "Brayden Burries",
    "status": "",
    "alcance": "",
    "bio": "Escolta | Arizona (EUA) | 1.93m | 6'4 | 20 anos",
    "posicao": "Escolta",
    "time": "Arizona (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Jamal Murray",
    "foto": "img/draft/Brayden-Burries.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "204f28aa-c73c-4f2c-bca1-169e649dac77"
  },
  {
    "rank": 34,
    "ordemCsv": "06v2",
    "slug": "dame-sarr",
    "nome": "Dame Sarr",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Duke (EUA) | 2.03m | 6'8 | 20 anos",
    "posicao": "Lateral",
    "time": "Duke (EUA)",
    "altura": "2.03m",
    "alturaImperial": "6'8",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Dame-Sarr.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "28acf91b-b2ed-4855-bec9-b94fbbeda662"
  },
  {
    "rank": 35,
    "ordemCsv": "06v3",
    "slug": "luigi-suigo",
    "nome": "Luigi Suigo",
    "status": "",
    "alcance": "",
    "bio": "Grande | Mega (SRB) | 2.18m | 7'2 | 19 anos",
    "posicao": "Grande",
    "time": "Mega (SRB)",
    "altura": "2.18m",
    "alturaImperial": "7'2",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Luigi-Suigo.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "ebd4c6ca-be62-4057-86a4-43e6d476c371"
  },
  {
    "rank": 36,
    "ordemCsv": "06v3j",
    "slug": "alex-condon",
    "nome": "Alex Condon",
    "status": "",
    "alcance": "",
    "bio": "Grande | Florida (EUA) | 2.11 | 6'11 | 21 anos",
    "posicao": "Grande",
    "time": "Florida (EUA)",
    "altura": "2.11",
    "alturaImperial": "6'11",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Isaiah Hartenstein",
    "foto": "img/draft/Alex-Condon.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "bec96dd9-9fe0-41f5-9214-f01c897689ad"
  },
  {
    "rank": 37,
    "ordemCsv": "06v3j4",
    "slug": "chris-cenac",
    "nome": "Chris Cenac",
    "status": "",
    "alcance": "",
    "bio": "Grande | Houston (EUA) | 2.08m | 6'10 | 19 anos",
    "posicao": "Grande",
    "time": "Houston (EUA)",
    "altura": "2.08m",
    "alturaImperial": "6'10",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Chris-Cenac-Jr.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "6fa88086-9522-4865-aa4c-7776007f3355"
  },
  {
    "rank": 38,
    "ordemCsv": "06v3j68",
    "slug": "david-mirkovic",
    "nome": "David Mirković",
    "status": "",
    "alcance": "",
    "bio": "Ala | Illinois (EUA) | 2.05m | 6'9 | 20 anos",
    "posicao": "Ala",
    "time": "Illinois (EUA)",
    "altura": "2.05m",
    "alturaImperial": "6'9",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/David-Mirkovic.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "3bfc4da9-49a1-4913-90e9-24ffa44cecae"
  },
  {
    "rank": 39,
    "ordemCsv": "06v3j6c",
    "slug": "patrick-ngongba-ii",
    "nome": "Patrick Ngongba II",
    "status": "",
    "alcance": "",
    "bio": "Grande | Duke (EUA) | 2.11m | 6'11 | 20 anos",
    "posicao": "Grande",
    "time": "Duke (EUA)",
    "altura": "2.11m",
    "alturaImperial": "6'11",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Patrick-Ngonba.png",
    "updatedAt": "2026-02-19T14:36:50Z",
    "id": "fdfd5b77-4642-4d38-9fcb-d782a608a662"
  },
  {
    "rank": 40,
    "ordemCsv": "06v3j6g",
    "slug": "karter-knox",
    "nome": "Karter Knox",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Arkansas (EUA) | 1.98m | 6'6 | 21 anos",
    "posicao": "Lateral",
    "time": "Arkansas (EUA)",
    "altura": "1.98m",
    "alturaImperial": "6'6",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Karter-Knox.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "72f83660-6938-43e8-a173-5f7c58510963"
  },
  {
    "rank": 41,
    "ordemCsv": "06v4",
    "slug": "yaxel-lendeborg",
    "nome": "Yaxel Lendeborg",
    "status": "",
    "alcance": "",
    "bio": "Ala | Michigan (EUA) | 2.06m | 6'9 | 23 anos",
    "posicao": "Ala",
    "time": "Michigan (EUA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "23 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Larry Nance Jr + PJ Tucker",
    "foto": "img/draft/Yaxel-Lendeborg.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "ce6e13be-9cd5-4020-b792-864fb04898ea"
  },
  {
    "rank": 42,
    "ordemCsv": "06v6",
    "slug": "noa-kouakou-heugue",
    "nome": "Noa Kouakou-Heugue",
    "status": "",
    "alcance": "",
    "bio": "Ala | Perth (AUS) | 2.04m | 6'8 | 19 anos",
    "posicao": "Ala",
    "time": "Perth (AUS)",
    "altura": "2.04m",
    "alturaImperial": "6'8",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Noa-KouakouHeugue.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "b301ae73-518c-4b74-a542-ec09138d68c8"
  },
  {
    "rank": 43,
    "ordemCsv": "06vag",
    "slug": "adam-atamna",
    "nome": "Adam Atamna",
    "status": "",
    "alcance": "",
    "bio": "Armador | ASVEL (FRA) | 1.95m | 6'5 | 18 anos",
    "posicao": "Armador",
    "time": "ASVEL (FRA)",
    "altura": "1.95m",
    "alturaImperial": "6'5",
    "idade": "18 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Goran Dragić",
    "foto": "img/draft/Adam-Atamna.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "177781d5-f9a5-4164-ab9b-aa6fe1c9ec15"
  },
  {
    "rank": 44,
    "ordemCsv": "06vb",
    "slug": "matt-able",
    "nome": "Matt Able",
    "status": "",
    "alcance": "",
    "bio": "Lateral | NC St. (EUA) | 1.96m | 6'5 | 19 anos",
    "posicao": "Lateral",
    "time": "NC St. (EUA)",
    "altura": "1.96m",
    "alturaImperial": "6'5",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Matt-Able.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "5bf58a45-b2e8-4470-a09a-dc86efe2d7f2"
  },
  {
    "rank": 45,
    "ordemCsv": "071",
    "slug": "massamba-diop",
    "nome": "Massamba Diop",
    "status": "",
    "alcance": "",
    "bio": "Grande | Arizona St. (EUA) | 2.16m | 7'1 | 21 anos",
    "posicao": "Grande",
    "time": "Arizona St. (EUA)",
    "altura": "2.16m",
    "alturaImperial": "7'1",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Massamba-Diop.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "b67851bc-792c-4247-9df0-f18cce926b62"
  },
  {
    "rank": 46,
    "ordemCsv": "076",
    "slug": "felipe-minzer",
    "nome": "Felipe Minzer",
    "status": "",
    "alcance": "",
    "bio": "Armador | HS (EUA) | 1.97m | 6'6 | 18 anos",
    "posicao": "Armador",
    "time": "HS (EUA)",
    "altura": "1.97m",
    "alturaImperial": "6'6",
    "idade": "18 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "3/4 do Manu Ginóbili",
    "foto": "img/draft/Felipe-Minzer.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "f34dad00-ea5a-494c-a0f2-920fc01706f4"
  },
  {
    "rank": 47,
    "ordemCsv": "078",
    "slug": "sergio-de-larrea",
    "nome": "Sergio De Larrea",
    "status": "",
    "alcance": "",
    "bio": "Armador | Valencia (ESP) | 1.96m | 6'5 | 20 anos",
    "posicao": "Armador",
    "time": "Valencia (ESP)",
    "altura": "1.96m",
    "alturaImperial": "6'5",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Sergio-De-Larrea.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "51b34cee-2910-4f70-9277-1d829dd777d4"
  },
  {
    "rank": 48,
    "ordemCsv": "07a",
    "slug": "moustapha-thiam",
    "nome": "Moustapha Thiam",
    "status": "",
    "alcance": "",
    "bio": "Grande | UCF (EUA) | 2.18m | 7'2 | 20 anos",
    "posicao": "Grande",
    "time": "UCF (EUA)",
    "altura": "2.18m",
    "alturaImperial": "7'2",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Moustapha-Thiam.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "68bcc783-37ff-48e5-9928-d1170c1a644f"
  },
  {
    "rank": 49,
    "ordemCsv": "07b8",
    "slug": "malachi-moreno",
    "nome": "Malachi Moreno",
    "status": "",
    "alcance": "",
    "bio": "Grande | Kentucky (EUA) | 2.11 | 6'11 | 19 anos",
    "posicao": "Grande",
    "time": "Kentucky (EUA)",
    "altura": "2.11",
    "alturaImperial": "6'11",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Malachi-Moreno.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "25fb0041-45af-4ba2-8006-7c1ebec91f8c"
  },
  {
    "rank": 50,
    "ordemCsv": "07c",
    "slug": "andrej-stojakovic",
    "nome": "Andrej Stojaković",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Illinois (EUA) | 2.01m | 6'7 | 21 anos",
    "posicao": "Lateral",
    "time": "Illinois (EUA)",
    "altura": "2.01m",
    "alturaImperial": "6'7",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Jordan Clarkson que defende",
    "foto": "img/draft/Andrej-Stojakovic.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "f10849ba-0ab5-46fa-9475-aee3f8f17d39"
  },
  {
    "rank": 51,
    "ordemCsv": "07c8",
    "slug": "morez-johnson-jr",
    "nome": "Morez Johnson Jr",
    "status": "",
    "alcance": "",
    "bio": "Grande | Michigan (EUA) | 2.06m | 6'9 | 20 anos",
    "posicao": "Grande",
    "time": "Michigan (EUA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Montrezl Harrell",
    "foto": "img/draft/Morez-Johnon-Jr.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "b179d2f4-5e99-4381-9364-073363966145"
  },
  {
    "rank": 52,
    "ordemCsv": "07ca",
    "slug": "flory-bidunga",
    "nome": "Flory Bidunga",
    "status": "",
    "alcance": "",
    "bio": "Grande | Kansas (EUA) | 2.06m | 6'9 | 21 anos",
    "posicao": "Grande",
    "time": "Kansas (EUA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Mini Jaxson Hayes com mais QI",
    "foto": "img/draft/Flory-Bidunga.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "c82e1a74-d280-4437-a4f8-9ce9c4c08fd9"
  },
  {
    "rank": 53,
    "ordemCsv": "07cc",
    "slug": "thierry-darlan",
    "nome": "Thierry Darlan",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Santa Clara (EUA) | 1.98m | 6'6 | 22 anos",
    "posicao": "Lateral",
    "time": "Santa Clara (EUA)",
    "altura": "1.98m",
    "alturaImperial": "6'6",
    "idade": "22 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "70% do Jalen Williams",
    "foto": "img/draft/Thierry-Darlan.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "1c3d7294-6dae-446a-8479-55d64b81f120"
  },
  {
    "rank": 54,
    "ordemCsv": "07j4",
    "slug": "jasper-johnson",
    "nome": "Jasper Johnson",
    "status": "",
    "alcance": "",
    "bio": "Escolta | Kentukcy (EUA) | 1.93m | 6'4 | 20 anos",
    "posicao": "Escolta",
    "time": "Kentukcy (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Bones Hyland que pensa",
    "foto": "img/draft/Jasper-Johnson.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "6abffb54-1f0b-4c30-9cf5-c9480159f526"
  },
  {
    "rank": 55,
    "ordemCsv": "07j5",
    "slug": "tyrone-riley-iv",
    "nome": "Tyrone Riley IV",
    "status": "",
    "alcance": "",
    "bio": "Lateral | San Francisco (EUA) | 1.98m | 6'6 | 20 anos",
    "posicao": "Lateral",
    "time": "San Francisco (EUA)",
    "altura": "1.98m",
    "alturaImperial": "6'6",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "50% do Jaylen Brown",
    "foto": "img/draft/Tyrone-Riley.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "c018f384-43b5-4f6b-b627-76144a90a934"
  },
  {
    "rank": 56,
    "ordemCsv": "07j8",
    "slug": "magoon-gwath",
    "nome": "Magoon Gwath",
    "status": "",
    "alcance": "",
    "bio": "Grande | San Diego St. (EUA) | 2.13m | 7'0 | 20 anos",
    "posicao": "Grande",
    "time": "San Diego St. (EUA)",
    "altura": "2.13m",
    "alturaImperial": "7'0",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Bol Bol teórico",
    "foto": "img/draft/Magoon-Gwath.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "1d4f0b16-293d-4239-beca-064c03f3a5a2"
  },
  {
    "rank": 57,
    "ordemCsv": "07jc",
    "slug": "isaiah-harwell",
    "nome": "Isaiah Harwell",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Houston (EUA) | 1.98m | 6'7 | 19 anos",
    "posicao": "Lateral",
    "time": "Houston (EUA)",
    "altura": "1.98m",
    "alturaImperial": "6'7",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Khris Middleton",
    "foto": "img/draft/Isaiah-Harwell.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "925e024a-ea56-4740-b49d-d08868119d90"
  },
  {
    "rank": 58,
    "ordemCsv": "07jg",
    "slug": "alvaro-folgueiras",
    "nome": "Alvaro Folgueiras",
    "status": "",
    "alcance": "",
    "bio": "Ala | Iowa (EUA) | 2.06m | 6'9 | 21 anos",
    "posicao": "Ala",
    "time": "Iowa (EUA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Boris Diaw",
    "foto": "img/draft/Alvaro-Folgueiras.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "48a4d06e-84d0-489d-b939-d259558ebc9d"
  },
  {
    "rank": 59,
    "ordemCsv": "07k",
    "slug": "anthony-robinson-ii",
    "nome": "Anthony Robinson II",
    "status": "",
    "alcance": "",
    "bio": "Armador | Missouri (EUA) | 1.88m | 6'2 | 21 anos",
    "posicao": "Armador",
    "time": "Missouri (EUA)",
    "altura": "1.88m",
    "alturaImperial": "6'2",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "70% de um Stephon Castle menor",
    "foto": "img/draft/Anthony-Robinson-II.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "047ad958-bbba-469d-bf1e-acdfa27edcf0"
  },
  {
    "rank": 60,
    "ordemCsv": "07m",
    "slug": "savo-drezgic",
    "nome": "Savo Drezgić",
    "status": "",
    "alcance": "",
    "bio": "Armador | Mega (SRB) | 1.92m | 6'4 | 19 anos",
    "posicao": "Armador",
    "time": "Mega (SRB)",
    "altura": "1.92m",
    "alturaImperial": "6'4",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Payton Pritchard",
    "foto": "img/draft/Savo-Drezgic.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "38fc56ba-5b0e-418f-9e78-9fdbc97425aa"
  },
  {
    "rank": 61,
    "ordemCsv": "07q",
    "slug": "keaton-wagler",
    "nome": "Keaton Wagler",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Illinois (EUA) | 1.98m | 6'7 | 19 anos",
    "posicao": "Lateral",
    "time": "Illinois (EUA)",
    "altura": "1.98m",
    "alturaImperial": "6'7",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Keaton-Wagler.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "df69867a-9b16-4d2d-967b-f1cf8288cbdb"
  },
  {
    "rank": 62,
    "ordemCsv": "07s",
    "slug": "killyan-toure",
    "nome": "Killyan Toure",
    "status": "",
    "alcance": "",
    "bio": "Escolta | Iowa St. (EUA) | 1.90m | 6'3 | 20 anos",
    "posicao": "Escolta",
    "time": "Iowa St. (EUA)",
    "altura": "1.90m",
    "alturaImperial": "6'3",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "Parador absoluto no ponto de ataque.",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Killyan-Toure.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "9f944b09-7818-447f-9cfe-de250ca08a1e"
  },
  {
    "rank": 63,
    "ordemCsv": "07t8",
    "slug": "london-jeminson",
    "nome": "London Jeminson",
    "status": "",
    "alcance": "",
    "bio": "Ala | Alabama (EUA) | 2.03m | 6'8 | 20 anos",
    "posicao": "Ala",
    "time": "Alabama (EUA)",
    "altura": "2.03m",
    "alturaImperial": "6'8",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/London-Jeminson.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "1fe63ed6-ae97-4563-95cd-e9a04a6d528d"
  },
  {
    "rank": 64,
    "ordemCsv": "08b",
    "slug": "paul-mcneil-jr",
    "nome": "Paul McNeil Jr",
    "status": "",
    "alcance": "",
    "bio": "Lateral | NC St. (EUA) | 1.96m | 6'5 | 20 anos",
    "posicao": "Lateral",
    "time": "NC St. (EUA)",
    "altura": "1.96m",
    "alturaImperial": "6'5",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Paul-McNeil-Jr.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "d473a495-a68f-4130-baaf-5aae0f5890da"
  },
  {
    "rank": 65,
    "ordemCsv": "08c8",
    "slug": "ivan-kharchenkov",
    "nome": "Ivan Kharchenkov",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Arizona (EUA) | 2.01m | 6'7 | 19 anos",
    "posicao": "Lateral",
    "time": "Arizona (EUA)",
    "altura": "2.01m",
    "alturaImperial": "6'7",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Ivan-Kharchenkov.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "65b04c8b-57c5-4ae1-b363-feaa71a75448"
  },
  {
    "rank": 66,
    "ordemCsv": "08d",
    "slug": "kayden-mingo",
    "nome": "Kayden Mingo",
    "status": "",
    "alcance": "",
    "bio": "Armador | Penn St. (EUA) | 1.91 | 6'3 | 19 anos",
    "posicao": "Armador",
    "time": "Penn St. (EUA)",
    "altura": "1.91",
    "alturaImperial": "6'3",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Kayden-Mingo.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "7fd2e611-e208-482c-a2c9-606964d5d428"
  },
  {
    "rank": 67,
    "ordemCsv": "09g",
    "slug": "cayden-boozer",
    "nome": "Cayden Boozer",
    "status": "",
    "alcance": "",
    "bio": "Armador | Duke (EUA) | 1.93m | 6'4 | 18 anos",
    "posicao": "Armador",
    "time": "Duke (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "18 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Tyus Jones",
    "foto": "img/draft/Cayden-Boozer.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "f8d049fb-39b9-4e8d-8b46-e68a81fddcf4"
  },
  {
    "rank": 68,
    "ordemCsv": "0b",
    "slug": "tahaad-pettiford",
    "nome": "Tahaad Pettiford",
    "status": "",
    "alcance": "",
    "bio": "Armador | Auburn (EUA) | 1.85m | 6'0 | 20 anos",
    "posicao": "Armador",
    "time": "Auburn (EUA)",
    "altura": "1.85m",
    "alturaImperial": "6'0",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Mini Terry Rozier",
    "foto": "img/draft/Tahaad-Pettiford.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "a77936a6-1cff-4ece-b914-e1a06487187a"
  },
  {
    "rank": 69,
    "ordemCsv": "0bg",
    "slug": "alijah-arenas",
    "nome": "Alijah Arenas",
    "status": "",
    "alcance": "",
    "bio": "Lateral | USC (EUA) | 1.97m | 6'6 | 19 anos",
    "posicao": "Lateral",
    "time": "USC (EUA)",
    "altura": "1.97m",
    "alturaImperial": "6'6",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Alijah-Arenas.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "0f4982e1-b752-4aa1-ab8d-bb9e8c5892af"
  },
  {
    "rank": 70,
    "ordemCsv": "0bhg",
    "slug": "bassala-bagayoko",
    "nome": "Bassala Bagayoko",
    "status": "",
    "alcance": "",
    "bio": "Grande | Bilbao (ESP) | 2.08m | 6'10 | 19 anos",
    "posicao": "Grande",
    "time": "Bilbao (ESP)",
    "altura": "2.08m",
    "alturaImperial": "6'10",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Clint Capela",
    "foto": "img/draft/Bassala-Bagayoko.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "522f3551-398b-4cf6-9855-b7b8e2ff1bc0"
  },
  {
    "rank": 71,
    "ordemCsv": "0bi",
    "slug": "jojo-tugler",
    "nome": "JoJo Tugler",
    "status": "",
    "alcance": "",
    "bio": "Grande | Houston (EUA) | 2.03m | 6'8 | 21 anos",
    "posicao": "Grande",
    "time": "Houston (EUA)",
    "altura": "2.03m",
    "alturaImperial": "6'8",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Kenneth Faried",
    "foto": "img/draft/JoJo-Tugler.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "23a76233-974e-4b14-92bb-e179aada0a37"
  },
  {
    "rank": 72,
    "ordemCsv": "0bk",
    "slug": "joshua-jefferson",
    "nome": "Joshua Jefferson",
    "status": "",
    "alcance": "",
    "bio": "Grande | Iowa St. (EUA) | 2.06m | 6'9 | 22 anos",
    "posicao": "Grande",
    "time": "Iowa St. (EUA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "22 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Joshua-Jefferson.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "629107a5-90c0-4a61-9df6-87a9e066fa83"
  },
  {
    "rank": 73,
    "ordemCsv": "0bl",
    "slug": "taylor-bol-bowen",
    "nome": "Taylor Bol-Bowen",
    "status": "",
    "alcance": "",
    "bio": "Ala | Alabama (EUA) | 2.08m | 6'10 | 22 anos",
    "posicao": "Ala",
    "time": "Alabama (EUA)",
    "altura": "2.08m",
    "alturaImperial": "6'10",
    "idade": "22 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Taylor-BolBowen.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "2d2c9248-fd62-4791-a26d-5a6442e6319d"
  },
  {
    "rank": 74,
    "ordemCsv": "0blg",
    "slug": "bangot-dak",
    "nome": "Bangot Dak",
    "status": "",
    "alcance": "",
    "bio": "Grande | Colorado (EUA) | 2.13m | 7'0 | 21 anos",
    "posicao": "Grande",
    "time": "Colorado (EUA)",
    "altura": "2.13m",
    "alturaImperial": "7'0",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Bangot-Dak.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "5b9dd481-582b-45ed-8acb-19c16488e2ab"
  },
  {
    "rank": 75,
    "ordemCsv": "0bm1o",
    "slug": "momo-faye",
    "nome": "Momo Faye",
    "status": "",
    "alcance": "",
    "bio": "Grande | Paris (FRA) | 2.06m | 6'9 | 21 anos",
    "posicao": "Grande",
    "time": "Paris (FRA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Precious Achiuwa",
    "foto": "img/draft/Momo-Faye.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "f528bc41-4234-450e-bc5b-5bb0d3eda484"
  },
  {
    "rank": 76,
    "ordemCsv": "0bm2",
    "slug": "baba-miller",
    "nome": "Baba Miller",
    "status": "",
    "alcance": "",
    "bio": "Ala | Cincinnati (EUA) | 2.11m | 6'11 | 22 anos",
    "posicao": "Ala",
    "time": "Cincinnati (EUA)",
    "altura": "2.11m",
    "alturaImperial": "6'11",
    "idade": "22 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Baba-Miller.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "13e7c51e-c7af-46a4-a87a-f3500d53fe80"
  },
  {
    "rank": 77,
    "ordemCsv": "0bm3",
    "slug": "khani-rooths",
    "nome": "Khani Rooths",
    "status": "",
    "alcance": "",
    "bio": "Ala | Louisville (EUA) | 2.08m | 6'10 | 20 anos",
    "posicao": "Ala",
    "time": "Louisville (EUA)",
    "altura": "2.08m",
    "alturaImperial": "6'10",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Khani-Roots.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "1153d4b6-d960-4f2c-87fe-24b656c2cb49"
  },
  {
    "rank": 78,
    "ordemCsv": "0bm8",
    "slug": "adrian-wooley",
    "nome": "Adrian Wooley",
    "status": "",
    "alcance": "",
    "bio": "Escolta | Louisville (EUA) | 1.95m | 6'5 | 20 anos",
    "posicao": "Escolta",
    "time": "Louisville (EUA)",
    "altura": "1.95m",
    "alturaImperial": "6'5",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Adrian-Wooley.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "8494f95f-2bb9-459b-8aa6-84dac089bbc9"
  },
  {
    "rank": 79,
    "ordemCsv": "0bo",
    "slug": "kam-williams",
    "nome": "Kam Williams",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Kentucky (EUA) | 2.03m | 6'8 | 20 anos",
    "posicao": "Lateral",
    "time": "Kentucky (EUA)",
    "altura": "2.03m",
    "alturaImperial": "6'8",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "50% do OG Anunoby",
    "foto": "img/draft/Kam-Williams.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "f127cfae-25eb-40b3-aaff-772f0217e986"
  },
  {
    "rank": 80,
    "ordemCsv": "0cd",
    "slug": "boogie-fland",
    "nome": "Boogie Fland",
    "status": "",
    "alcance": "",
    "bio": "Armador | Florida (EUA) | 1.88m | 6'2 | 19 anos",
    "posicao": "Armador",
    "time": "Florida (EUA)",
    "altura": "1.88m",
    "alturaImperial": "6'2",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Darius Garland que defende menos",
    "foto": "img/draft/Boogie-Fland.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "1fcd2e65-db1b-45f9-a08a-aef4b550a6f8"
  },
  {
    "rank": 81,
    "ordemCsv": "0cg",
    "slug": "alexandros-samodurov",
    "nome": "Alexandros Samodurov",
    "status": "",
    "alcance": "",
    "bio": "Grande | Panathinaikos (GRE) | 2.11 | 6'11 | 21 anos",
    "posicao": "Grande",
    "time": "Panathinaikos (GRE)",
    "altura": "2.11",
    "alturaImperial": "6'11",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Alexandros-Samodurov.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "9ef49046-b54d-4216-a945-9896517f16ec"
  },
  {
    "rank": 82,
    "ordemCsv": "0ch",
    "slug": "jt-toppin",
    "nome": "JT Toppin",
    "status": "",
    "alcance": "",
    "bio": "Grande | Texas Tech (EUA) | 2.06m | 6'9 | 21 anos",
    "posicao": "Grande",
    "time": "Texas Tech (EUA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Precious Achiuwa",
    "foto": "img/draft/JT-Toppin.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "039f07c3-407b-40ac-9efe-802b130a7d7f"
  },
  {
    "rank": 83,
    "ordemCsv": "0chg",
    "slug": "dovydas-buika",
    "nome": "Dovydas Buika",
    "status": "",
    "alcance": "",
    "bio": "Armador | Zalgiris (LTU) | 1.98m | 6'7 | 19 anos",
    "posicao": "Armador",
    "time": "Zalgiris (LTU)",
    "altura": "1.98m",
    "alturaImperial": "6'7",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Dovydas-Buika.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "ba22190a-3c3f-49e4-a165-0db880cb8e38"
  },
  {
    "rank": 84,
    "ordemCsv": "0d8",
    "slug": "miles-byrd",
    "nome": "Miles Byrd",
    "status": "",
    "alcance": "",
    "bio": "Lateral | San Diego St. (EUA) | 2.01m | 6'7 | 21 anos",
    "posicao": "Lateral",
    "time": "San Diego St. (EUA)",
    "altura": "2.01m",
    "alturaImperial": "6'7",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Matisse Thybulle",
    "foto": "img/draft/Miles-Byrd.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "f2cbaf9f-0de3-442c-956b-ba204c4e6ccc"
  },
  {
    "rank": 85,
    "ordemCsv": "0dg",
    "slug": "kiyan-anthony",
    "nome": "Kiyan Anthony",
    "status": "",
    "alcance": "",
    "bio": "Escolta | Syracuse (EUA) | 1.96m | 6'6 | 19 anos",
    "posicao": "Escolta",
    "time": "Syracuse (EUA)",
    "altura": "1.96m",
    "alturaImperial": "6'6",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Kiyan-Anthony.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "5806969c-f5c4-4963-a3ae-095e4a959a4c"
  },
  {
    "rank": 86,
    "ordemCsv": "0do",
    "slug": "omer-mayer",
    "nome": "Omer Mayer",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Purdue (EUA) | 1.93m | 6'4 | 19 anos",
    "posicao": "Lateral",
    "time": "Purdue (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Omer-Mayer.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "71ffb62f-59b7-4f85-a284-a362f1266db4"
  },
  {
    "rank": 87,
    "ordemCsv": "0e",
    "slug": "shon-abaev",
    "nome": "Shon Abaev",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Cincinnati (EUA) | 2.01m | 6'7 | 19 anos",
    "posicao": "Lateral",
    "time": "Cincinnati (EUA)",
    "altura": "2.01m",
    "alturaImperial": "6'7",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Shon-Abaev.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "a073c7ed-16d6-4915-a954-5747089ee39c"
  },
  {
    "rank": 88,
    "ordemCsv": "0eg",
    "slug": "ognjen-srzentic",
    "nome": "Ognjen Srzentić",
    "status": "",
    "alcance": "",
    "bio": "Escolta | Mega (SRB) | 2.00 | 6'7 | 19 anos",
    "posicao": "Escolta",
    "time": "Mega (SRB)",
    "altura": "2.00",
    "alturaImperial": "6'7",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Ognjen-Srzentić.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "cc187e6d-bf3c-4940-87d4-cb92df22086d"
  },
  {
    "rank": 89,
    "ordemCsv": "0es",
    "slug": "trevon-brazile",
    "nome": "Trevon Brazile",
    "status": "",
    "alcance": "",
    "bio": "Ala | Arkansas (EUA) | 2.06 | 6'9 | 23 anos",
    "posicao": "Ala",
    "time": "Arkansas (EUA)",
    "altura": "2.06",
    "alturaImperial": "6'9",
    "idade": "23 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Trevor-Brazile.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "79b51766-2d6b-45ce-8728-73d59fd5fecd"
  },
  {
    "rank": 90,
    "ordemCsv": "0f4g",
    "slug": "dayan-nessah",
    "nome": "Dayan Nessah",
    "status": "",
    "alcance": "",
    "bio": "Ala | Cleveland St. (EUA) | 2.00m | 6'7 | 20 anos",
    "posicao": "Ala",
    "time": "Cleveland St. (EUA)",
    "altura": "2.00m",
    "alturaImperial": "6'7",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Dayan-Nessah.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "7f25125b-c113-46b9-8670-51c6bd05d9da"
  },
  {
    "rank": 91,
    "ordemCsv": "0f5",
    "slug": "mackenzie-mgbako",
    "nome": "Mackenzie Mgbako",
    "status": "",
    "alcance": "",
    "bio": "Ala | Texas A&M (EUA) | 2.03m | 6'8 | 21 anos",
    "posicao": "Ala",
    "time": "Texas A&M (EUA)",
    "altura": "2.03m",
    "alturaImperial": "6'8",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Harrison Barnes que chuta mais do que defende",
    "foto": "img/draft/Mackenzie-Mgbako.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "d9f169b9-5059-4fd7-85e7-695cb4db5f6b"
  },
  {
    "rank": 92,
    "ordemCsv": "0fo",
    "slug": "michael-ruzic",
    "nome": "Michael Ruzic",
    "status": "",
    "alcance": "",
    "bio": "Ala | Joventut (EUA) | 2.03m | 6'8 | 19 anos",
    "posicao": "Ala",
    "time": "Joventut (EUA)",
    "altura": "2.03m",
    "alturaImperial": "6'8",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Santi Aldama",
    "foto": "img/draft/Michael-Ruzic.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "5a91e6cf-82f6-4cc9-8646-f2830fe46a83"
  },
  {
    "rank": 93,
    "ordemCsv": "0fq",
    "slug": "eric-reibe",
    "nome": "Eric Reibe",
    "status": "",
    "alcance": "",
    "bio": "Grande | UConn (EUA) | 2.13m | 7'0 | 19 anos",
    "posicao": "Grande",
    "time": "UConn (EUA)",
    "altura": "2.13m",
    "alturaImperial": "7'0",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Eric-Reibe.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "54ef686a-fc64-4e43-9a23-f45504b5cb0f"
  },
  {
    "rank": 94,
    "ordemCsv": "0fs",
    "slug": "malique-lewis",
    "nome": "Malique Lewis",
    "status": "",
    "alcance": "",
    "bio": "Ala | SEM (AUS) | 2.02m | 6'8 | 21 anos",
    "posicao": "Ala",
    "time": "SEM (AUS)",
    "altura": "2.02m",
    "alturaImperial": "6'8",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Malique-Lewis.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "3230cd7c-017e-4d7e-899e-3f33a39f5dd2"
  },
  {
    "rank": 95,
    "ordemCsv": "0fsg",
    "slug": "pavle-backo",
    "nome": "Pavle Bačko",
    "status": "",
    "alcance": "",
    "bio": "Grande | Mega (SRB) | 2.13m | 7'0 | 18 anos",
    "posicao": "Grande",
    "time": "Mega (SRB)",
    "altura": "2.13m",
    "alturaImperial": "7'0",
    "idade": "18 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Pavle-Backo.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "970970e1-cb48-4678-acc7-b0d6dd6ce473"
  },
  {
    "rank": 96,
    "ordemCsv": "0fsk",
    "slug": "samis-calderon",
    "nome": "Samis Calderon",
    "status": "",
    "alcance": "",
    "bio": "Ala | Kansas (EUA) | 2.03m | 6'8 | 21 anos",
    "posicao": "Ala",
    "time": "Kansas (EUA)",
    "altura": "2.03m",
    "alturaImperial": "6'8",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Samis-Calderon.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "33f2826a-c837-4d53-8302-92edb1d6f77f"
  },
  {
    "rank": 97,
    "ordemCsv": "0fso",
    "slug": "kanon-catchings",
    "nome": "Kanon Catchings",
    "status": "",
    "alcance": "",
    "bio": "Armador | BYU (EUA) | 2.06m | 6'9 | 20 anos",
    "posicao": "Armador",
    "time": "BYU (EUA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Jaden McDaniels",
    "foto": "img/draft/Kanon-Catchings.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "f0349d10-5523-4979-aaf8-c764738069db"
  },
  {
    "rank": 98,
    "ordemCsv": "0ft",
    "slug": "wesley-yates-iii",
    "nome": "Wesley Yates III",
    "status": "",
    "alcance": "",
    "bio": "Escolta | Washington (EUA) | 1.93m | 6'4 | 21 anos",
    "posicao": "Escolta",
    "time": "Washington (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Wesley-Yates.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "6b648833-ea69-4a71-8ec0-ca2e5e5be9f3"
  },
  {
    "rank": 99,
    "ordemCsv": "0gg",
    "slug": "otega-oweh",
    "nome": "Otega Oweh",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Kentucky (EUA) | 1.93m | 6'4 | 23 anos",
    "posicao": "Lateral",
    "time": "Kentucky (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "23 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Otega-Oweh.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "765f58ea-a783-4db4-b94d-b8626ac24d4e"
  },
  {
    "rank": 100,
    "ordemCsv": "0h",
    "slug": "daniel-jacobsen",
    "nome": "Daniel Jacobsen",
    "status": "",
    "alcance": "",
    "bio": "Grande | Purdue (EUA) | 2.21m | 7'3 | 20 anos",
    "posicao": "Grande",
    "time": "Purdue (EUA)",
    "altura": "2.21m",
    "alturaImperial": "7'3",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Daniel-Jacobsen.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "bb7a415f-a86a-49e6-946e-eb0c827853f6"
  },
  {
    "rank": 101,
    "ordemCsv": "0j",
    "slug": "coen-carr",
    "nome": "Coen Carr",
    "status": "",
    "alcance": "",
    "bio": "Ala | Michigan St. (EUA) | 1.98m | 6'7 | 21 anos",
    "posicao": "Ala",
    "time": "Michigan St. (EUA)",
    "altura": "1.98m",
    "alturaImperial": "6'7",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Derrick Jones Jr",
    "foto": "img/draft/Coen-Carr.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "27a146ec-f3d6-4732-bf07-e8f9fdbe96f6"
  },
  {
    "rank": 102,
    "ordemCsv": "0k",
    "slug": "reynan-dos-santos",
    "nome": "Reynan dos Santos",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Capitanes (MEX) | 1.95m | 6'5 | 22 anos",
    "posicao": "Lateral",
    "time": "Capitanes (MEX)",
    "altura": "1.95m",
    "alturaImperial": "6'5",
    "idade": "22 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Gary Payton II",
    "foto": "img/draft/Reynan-dos-Santos.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "ea85a0b5-0978-4421-8f12-ae58ce899f9c"
  },
  {
    "rank": 103,
    "ordemCsv": "0l",
    "slug": "tomislav-ivisic",
    "nome": "Tomislav Ivišić",
    "status": "",
    "alcance": "",
    "bio": "Grande | Illinois (EUA) | 2.16m | 7'1 | 22 anos",
    "posicao": "Grande",
    "time": "Illinois (EUA)",
    "altura": "2.16m",
    "alturaImperial": "7'1",
    "idade": "22 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "60% do Brook Lopez",
    "foto": "img/draft/Tomislav-Ivisic.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "1c0ea879-5b79-4795-9f9a-5a1810b06a78"
  },
  {
    "rank": 104,
    "ordemCsv": "0m",
    "slug": "richie-saunders",
    "nome": "Richie Saunders",
    "status": "",
    "alcance": "",
    "bio": "Lateral | BYU (EUA) | 1.96m | 6'5 | 24 anos",
    "posicao": "Lateral",
    "time": "BYU (EUA)",
    "altura": "1.96m",
    "alturaImperial": "6'5",
    "idade": "24 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Grayson Allen muito menos atlético",
    "foto": "img/draft/Richie-Saunders.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "b0878642-f4c2-46f2-8095-0b2f9e6d7140"
  },
  {
    "rank": 105,
    "ordemCsv": "0n",
    "slug": "hugo-facorat",
    "nome": "Hugo Facorat",
    "status": "",
    "alcance": "",
    "bio": "Ala | HS (EUA) | 2.10m | 6'11 | 19 anos",
    "posicao": "Ala",
    "time": "HS (EUA)",
    "altura": "2.10m",
    "alturaImperial": "6'11",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Hugo-Facorat.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "70366c59-872c-4531-a07f-9afa3138732d"
  },
  {
    "rank": 106,
    "ordemCsv": "0o",
    "slug": "mario-saint-supery",
    "nome": "Mario Saint-Supery",
    "status": "",
    "alcance": "",
    "bio": "Armador | Gonzaga (EUA) | 1.90m | 6'3 | 20 anos",
    "posicao": "Armador",
    "time": "Gonzaga (EUA)",
    "altura": "1.90m",
    "alturaImperial": "6'3",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Mario-Supery.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "d5cc3281-a56b-46b1-9b31-a5943c1e6ff5"
  },
  {
    "rank": 107,
    "ordemCsv": "0og",
    "slug": "gabriel-landeira",
    "nome": "Gabriel Landeira",
    "status": "",
    "alcance": "",
    "bio": "Armador | Georgetown (EUA) | 1.97m | 6'6 | 21 anos",
    "posicao": "Armador",
    "time": "Georgetown (EUA)",
    "altura": "1.97m",
    "alturaImperial": "6'6",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Gabriel-Landeira.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "a1b6a7b6-50cd-44b1-89be-ba4533ce7ddf"
  },
  {
    "rank": 108,
    "ordemCsv": "0p",
    "slug": "winicius-silva",
    "nome": "Winicius Silva",
    "status": "",
    "alcance": "",
    "bio": "Grande | Minas (BRA) | 2.05m | 6'9 | 21 anos",
    "posicao": "Grande",
    "time": "Minas (BRA)",
    "altura": "2.05m",
    "alturaImperial": "6'9",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Tristan Thompson",
    "foto": "img/draft/Wini-Silva.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "f97a022f-ec35-46a1-9585-0b9367079583"
  },
  {
    "rank": 109,
    "ordemCsv": "0q",
    "slug": "francesco-ferrari",
    "nome": "Francesco Ferrari",
    "status": "",
    "alcance": "",
    "bio": "Ala | United Eagles (ITA) | 2.04m | 6'8 | 20 anos",
    "posicao": "Ala",
    "time": "United Eagles (ITA)",
    "altura": "2.04m",
    "alturaImperial": "6'8",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Francesco-Ferrari.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "f5177658-7c0a-42be-8fa9-a82494d3eae3"
  },
  {
    "rank": 110,
    "ordemCsv": "0qg",
    "slug": "johann-grunloh",
    "nome": "Johann Grunloh",
    "status": "",
    "alcance": "",
    "bio": "Grande | Virginia (EUA) | 2.09m | 6'10 | 20 anos",
    "posicao": "Grande",
    "time": "Virginia (EUA)",
    "altura": "2.09m",
    "alturaImperial": "6'10",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Johann-Grunloh.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "33547fc8-9758-4ae8-9c42-e201124cc480"
  },
  {
    "rank": 111,
    "ordemCsv": "0r",
    "slug": "donnie-freeman",
    "nome": "Donnie Freeman",
    "status": "",
    "alcance": "",
    "bio": "Ala | Syracuse (EUA) | 2.06m | 6'9 | 20 anos",
    "posicao": "Ala",
    "time": "Syracuse (EUA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Donnie-Freeman.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "ba986506-8752-429b-9e14-33579524f617"
  },
  {
    "rank": 112,
    "ordemCsv": "0tg",
    "slug": "darrion-williams",
    "nome": "Darrion Williams",
    "status": "",
    "alcance": "",
    "bio": "Ala | NC St. (EUA) | 1.98m | 6'7 | 23 anos",
    "posicao": "Ala",
    "time": "NC St. (EUA)",
    "altura": "1.98m",
    "alturaImperial": "6'7",
    "idade": "23 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Grant Williams",
    "foto": "img/draft/Darrion-Williams.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "a9b22069-0cc4-4bd3-993c-1c6210d00737"
  },
  {
    "rank": 113,
    "ordemCsv": "0u",
    "slug": "joson-sanon",
    "nome": "Joson Sanon",
    "status": "",
    "alcance": "",
    "bio": "Escolta | St.John's (EUA) | 1.96m | 6'5 | 20 anos",
    "posicao": "Escolta",
    "time": "St.John's (EUA)",
    "altura": "1.96m",
    "alturaImperial": "6'5",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Joson-Sanon.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "ad27dd4b-6591-4d6b-a5bd-64753fa558bb"
  },
  {
    "rank": 114,
    "ordemCsv": "0v",
    "slug": "jacob-furphy",
    "nome": "Jacob Furphy",
    "status": "",
    "alcance": "",
    "bio": "Lateral | UConn (EUA) | 1.93m | 6'4 | 19 anos",
    "posicao": "Lateral",
    "time": "UConn (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Jacob-Furphy.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "76a99a1f-96c6-442f-9145-3d14642f97b3"
  },
  {
    "rank": 115,
    "ordemCsv": "18",
    "slug": "robert-wright-iii",
    "nome": "Robert Wright III",
    "status": "",
    "alcance": "",
    "bio": "Armador | BYU (EUA) | 1.85m | 6'0 | 20 anos",
    "posicao": "Armador",
    "time": "BYU (EUA)",
    "altura": "1.85m",
    "alturaImperial": "6'0",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Trey Burke",
    "foto": "img/draft/Rob-Wright.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "62d7d9ec-6766-400c-bb74-274bd1ba3406"
  },
  {
    "rank": 116,
    "ordemCsv": "1c",
    "slug": "augusto-cassia",
    "nome": "Augusto Cassiá",
    "status": "",
    "alcance": "",
    "bio": "Grande | Ole Miss (EUA) | 2.03m | 6'8 | 23 anos",
    "posicao": "Grande",
    "time": "Ole Miss (EUA)",
    "altura": "2.03m",
    "alturaImperial": "6'8",
    "idade": "23 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Augusto-Cassiá.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "51483527-d36d-4b52-8354-92851217ae7e"
  },
  {
    "rank": 117,
    "ordemCsv": "2g",
    "slug": "xaivian-lee",
    "nome": "Xaivian Lee",
    "status": "",
    "alcance": "",
    "bio": "Armador | Florida (EUA) | 1.93m | 6'4 | 22 anos",
    "posicao": "Armador",
    "time": "Florida (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "22 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Xaivian-Lee.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "14d21fd6-1388-42ce-9941-eb6c053d6262"
  },
  {
    "rank": 118,
    "ordemCsv": "3",
    "slug": "jonas-boulefaa",
    "nome": "Jonas Boulefaa",
    "status": "",
    "alcance": "",
    "bio": "Ala | ADA Blois (FRA) | 2.06m | 6'9 | 19 anos",
    "posicao": "Ala",
    "time": "ADA Blois (FRA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Royce O’Neale",
    "foto": "img/draft/Jonas-Boulefaa.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "4b1b0160-2a39-47fd-a6e3-ab5a893d6869"
  },
  {
    "rank": 119,
    "ordemCsv": "38",
    "slug": "ian-jackson",
    "nome": "Ian Jackson",
    "status": "",
    "alcance": "",
    "bio": "Escolta | St. John's (EUA) | 1.93m | 6'4 | 21 anos",
    "posicao": "Escolta",
    "time": "St. John's (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Monta Ellis",
    "foto": "img/draft/Ian-Jackson.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "95872393-f87e-4d61-bb9c-d1a92a4ba51c"
  },
  {
    "rank": 120,
    "ordemCsv": "3a",
    "slug": "milos-uzan",
    "nome": "Milos Uzan",
    "status": "",
    "alcance": "",
    "bio": "Escolta | Houston (EUA) | 1.93m | 6'4 | 23 anos",
    "posicao": "Escolta",
    "time": "Houston (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "23 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Milos-Uzan.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "01480896-f23e-4de5-b369-3aebe8378931"
  },
  {
    "rank": 121,
    "ordemCsv": "3cg",
    "slug": "alex-karaban",
    "nome": "Alex Karaban",
    "status": "",
    "alcance": "",
    "bio": "Lateral | UConn (EUA) | 2.03m | 6'8 | 24 anos",
    "posicao": "Lateral",
    "time": "UConn (EUA)",
    "altura": "2.03m",
    "alturaImperial": "6'8",
    "idade": "24 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Joe Ingles",
    "foto": "img/draft/Alex-Karaban.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "8ebf2831-18ae-467f-8326-b0cf8d37ffce"
  },
  {
    "rank": 122,
    "ordemCsv": "3e4",
    "slug": "bruce-thornton",
    "nome": "Bruce Thornton",
    "status": "",
    "alcance": "",
    "bio": "Armador | Ohio St. (EUA) | 1.88m | 6'2 | 22 anos",
    "posicao": "Armador",
    "time": "Ohio St. (EUA)",
    "altura": "1.88m",
    "alturaImperial": "6'2",
    "idade": "22 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Bruce-Thornton.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "0a5d0444-6127-4a4c-81b6-e27d6ef09686"
  },
  {
    "rank": 123,
    "ordemCsv": "3eo",
    "slug": "milan-momcilovic",
    "nome": "Milan Momcilovic",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Iowa St. (EUA) | 2.03m | 6'8 | 21 anos",
    "posicao": "Lateral",
    "time": "Iowa St. (EUA)",
    "altura": "2.03m",
    "alturaImperial": "6'8",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "Mini Lauri Markkanen",
    "foto": "img/draft/Milan-Momcilovic.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "b00c142b-fee3-46e2-b596-4ac991412b8b"
  },
  {
    "rank": 124,
    "ordemCsv": "3es",
    "slug": "zuby-ejiofor",
    "nome": "Zuby Ejiofor",
    "status": "",
    "alcance": "",
    "bio": "Grande | St.John's (EUA) | 2.06m | 6'9 | 22 anos",
    "posicao": "Grande",
    "time": "St.John's (EUA)",
    "altura": "2.06m",
    "alturaImperial": "6'9",
    "idade": "22 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "img/draft/Zuby-Ejiofor.png",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "94ebf9e3-b1a6-415d-905b-b0ba72d59aec"
  },
  {
    "rank": 125,
    "ordemCsv": "3f0",
    "slug": "billy-richmond-iii",
    "nome": "Billy Richmond III",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Alabama (EUA) | 1.96m | 6'5 | 20 anos",
    "posicao": "Lateral",
    "time": "Alabama (EUA)",
    "altura": "1.96m",
    "alturaImperial": "6'5",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "165ffc52-d9f9-4c04-8eb1-84ca1c657ce2"
  },
  {
    "rank": 126,
    "ordemCsv": "3f1",
    "slug": "ryan-conwell",
    "nome": "Ryan Conwell",
    "status": "",
    "alcance": "",
    "bio": "Armador | Louisville (EUA) | 1.93m | 6'4 | 22 anos",
    "posicao": "Armador",
    "time": "Louisville (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "22 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "48ce688f-32ba-4044-a8aa-585a90a93946"
  },
  {
    "rank": 127,
    "ordemCsv": "3f2",
    "slug": "tucker-devries",
    "nome": "Tucker DeVries",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Indiana (EUA) | 2.01m | 6'7 | 23 anos",
    "posicao": "Lateral",
    "time": "Indiana (EUA)",
    "altura": "2.01m",
    "alturaImperial": "6'7",
    "idade": "23 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "acb7a21a-3fb1-4cfd-bc69-baccb604e1e6"
  },
  {
    "rank": 128,
    "ordemCsv": "3f3",
    "slug": "john-blackwell",
    "nome": "John Blackwell",
    "status": "",
    "alcance": "",
    "bio": "Escolta | Wisconsin (EUA) | 1.93m | 6'4 | 21 anos",
    "posicao": "Escolta",
    "time": "Wisconsin (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "21 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "c88b39b5-ef86-4978-8dce-f5e80fe76dfd"
  },
  {
    "rank": 129,
    "ordemCsv": "3f4",
    "slug": "chase-ross",
    "nome": "Chase Ross",
    "status": "",
    "alcance": "",
    "bio": "Armador | Marquette (EUA) | 1.96m | 6'5 | 23 anos",
    "posicao": "Armador",
    "time": "Marquette (EUA)",
    "altura": "1.96m",
    "alturaImperial": "6'5",
    "idade": "23 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "09018c21-908c-4fa8-884b-0606c60e652d"
  },
  {
    "rank": 130,
    "ordemCsv": "3f5",
    "slug": "pedro-pastre",
    "nome": "Pedro Pastre",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Pinheiros (BRA) | 1.97m | 6'6 | 18 anos",
    "posicao": "Lateral",
    "time": "Pinheiros (BRA)",
    "altura": "1.97m",
    "alturaImperial": "6'6",
    "idade": "18 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "3c8249da-00c4-42a6-82e9-2b78b2f5532e"
  },
  {
    "rank": 131,
    "ordemCsv": "3f7",
    "slug": "trey-mckenney",
    "nome": "Trey McKenney",
    "status": "",
    "alcance": "",
    "bio": "Lateral | Michigan (EUA) | 1.93m | 6'4 | 19 anos",
    "posicao": "Lateral",
    "time": "Michigan (EUA)",
    "altura": "1.93m",
    "alturaImperial": "6'4",
    "idade": "19 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "c7e8834b-9963-40bc-86b7-b563a7a43240"
  },
  {
    "rank": 132,
    "ordemCsv": "3f8",
    "slug": "ebuka-okorie",
    "nome": "Ebuka Okorie",
    "status": "",
    "alcance": "",
    "bio": "Armador | Stanford (EUA) | 1.88m | 6'2 | 24 anos",
    "posicao": "Armador",
    "time": "Stanford (EUA)",
    "altura": "1.88m",
    "alturaImperial": "6'2",
    "idade": "24 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "c811f884-da49-423e-961c-d2d9280725cf"
  },
  {
    "rank": 133,
    "ordemCsv": "3f9",
    "slug": "baye-ndongo",
    "nome": "Baye Ndongo",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "1ba26f6a-25b0-4a65-a6da-3ac53e1b9c9b"
  },
  {
    "rank": 134,
    "ordemCsv": "3fa",
    "slug": "amael-l-etang",
    "nome": "Amael L'Etang",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "fc658070-e0a4-4e8b-af50-7cd7de0b1c3e"
  },
  {
    "rank": 135,
    "ordemCsv": "3fb",
    "slug": "motiejus-krivas",
    "nome": "Motiejus Krivas",
    "status": "",
    "alcance": "8-20",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2026-02-19T14:37:38Z",
    "id": "15975912-b05c-4040-84e6-bbc53b6f3207"
  },
  {
    "rank": 136,
    "ordemCsv": "3fc",
    "slug": "bryson-tiller",
    "nome": "Bryson Tiller",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "1212d0bd-70fa-48a8-8700-34a29d2f4c8c"
  },
  {
    "rank": 137,
    "ordemCsv": "3fd",
    "slug": "cam-ward",
    "nome": "Cam Ward",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "e1d948f3-1f53-47ec-8f47-14998f2ed7ab"
  },
  {
    "rank": 138,
    "ordemCsv": "3fe",
    "slug": "shelton-henderson",
    "nome": "Shelton Henderson",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "0d5a613c-95e1-442b-ab6f-36af021adac6"
  },
  {
    "rank": 139,
    "ordemCsv": "3ff",
    "slug": "duke-harris",
    "nome": "Duke Harris",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "61bdf336-f6a4-4798-9f8d-e6839d11ae87"
  },
  {
    "rank": 140,
    "ordemCsv": "3fg",
    "slug": "nate-bittle",
    "nome": "Nate Bittle",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "5e22bf07-f6cd-481d-b3be-38e8efaae69b"
  },
  {
    "rank": 141,
    "ordemCsv": "3fg8",
    "slug": "sananda-fru",
    "nome": "Sananda Fru",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "6e327a0f-8efb-4eff-a14e-3800729a7f89"
  },
  {
    "rank": 142,
    "ordemCsv": "3fgg",
    "slug": "tamin-lipsey",
    "nome": "Tamin Lipsey",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "9e4c0a2a-27d6-435f-be17-90ffb22e9e8e"
  },
  {
    "rank": 143,
    "ordemCsv": "3fgo",
    "slug": "jeremy-fears-jr",
    "nome": "Jeremy Fears Jr",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "9214a32b-f9a9-4d01-9b70-2b01cdc92029"
  },
  {
    "rank": 144,
    "ordemCsv": "3fh",
    "slug": "kohl-rosario",
    "nome": "Kohl Rosario",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "7f8d6a7e-70a3-464e-a752-e01220756ecd"
  },
  {
    "rank": 145,
    "ordemCsv": "3fh8",
    "slug": "jordan-scott",
    "nome": "Jordan Scott",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "5dc0a140-17a6-450a-bf04-19e7d7f34531"
  },
  {
    "rank": 146,
    "ordemCsv": "3fhg",
    "slug": "jacob-cofie",
    "nome": "Jacob Cofie",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "d4c3cd98-6913-4913-9e37-dc650780057b"
  },
  {
    "rank": 147,
    "ordemCsv": "3fho",
    "slug": "jaden-toombs",
    "nome": "Jaden Toombs",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "2c7b1a6a-514c-4951-948d-a2de7413d65b"
  },
  {
    "rank": 148,
    "ordemCsv": "3fi",
    "slug": "ja-kobi-gillespie",
    "nome": "Ja'Kobi Gillespie",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "3b5ad078-a24e-4389-8dcf-089258f5c289"
  },
  {
    "rank": 149,
    "ordemCsv": "3fi8",
    "slug": "tyler-tanner",
    "nome": "Tyler Tanner",
    "status": "",
    "alcance": "",
    "bio": "Armador | Vanderbilt (EUA) | 1.83m | 6'0 | 20 anos",
    "posicao": "Armador",
    "time": "Vanderbilt (EUA)",
    "altura": "1.83m",
    "alturaImperial": "6'0",
    "idade": "20 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2026-01-05T01:08:04Z",
    "id": "4d66efcb-f54c-4242-8144-e13765ca2e5c"
  },
  {
    "rank": 150,
    "ordemCsv": "3fig",
    "slug": "sebastian-williams-adams",
    "nome": "Sebastian Williams-Adams",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "37c50bfb-bcdc-4341-878f-5d72fbda3e40"
  },
  {
    "rank": 151,
    "ordemCsv": "3fio",
    "slug": "blake-harper",
    "nome": "Blake Harper",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "e6b5fc39-afd8-433f-8e7d-b7283a3ae462"
  },
  {
    "rank": 152,
    "ordemCsv": "3fj",
    "slug": "robert-mccray-v",
    "nome": "Robert McCray V",
    "status": "",
    "alcance": "",
    "bio": "",
    "posicao": "",
    "time": "",
    "altura": "",
    "alturaImperial": "",
    "idade": "",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2025-12-22T03:41:03Z",
    "id": "e95cef47-c3a0-4ab0-845e-0ca70a2882ba"
  },
  {
    "rank": 153,
    "ordemCsv": "3fj8",
    "slug": "boopie-milller",
    "nome": "Boopie Milller",
    "status": "",
    "alcance": "",
    "bio": "Armador | SMU (EUA) | 1.85m | 6'1 | 23 anos",
    "posicao": "Armador",
    "time": "SMU (EUA)",
    "altura": "1.85m",
    "alturaImperial": "6'1",
    "idade": "23 anos",
    "arquetipoOfensivo": "",
    "arquetipoDefensivo": "",
    "motivoEscolha": "",
    "chaveDesenvolvimento": "",
    "tetoPiso": "",
    "espelho": "",
    "foto": "",
    "updatedAt": "2026-01-05T01:07:38Z",
    "id": "c4fe89c9-7e7c-4dce-b680-22bfcd736b6f"
  }
];
