const rankingsDisponiveis = [
  {
    "slug": "2006",
    "titulo": "ranking [2006]",
    "pagina": "ranking-2006.html",
    "imagem": "img/rankings/ranking-2006.png",
    "total": 15
  },
  {
    "slug": "2007",
    "titulo": "ranking [2007]",
    "pagina": "ranking-2007.html",
    "imagem": "img/rankings/ranking-2007.png",
    "total": 20
  },
  {
    "slug": "2008",
    "titulo": "ranking [2008]",
    "pagina": "ranking-2008.html",
    "imagem": "img/rankings/ranking-2008.png",
    "total": 20
  },
  {
    "slug": "2009",
    "titulo": "ranking [2009]",
    "pagina": "ranking-2009.html",
    "imagem": "img/rankings/ranking-2009.png",
    "total": 20
  },
  {
    "slug": "2010",
    "titulo": "ranking [2010]",
    "pagina": "ranking-2010.html",
    "imagem": "img/rankings/ranking-2010.png",
    "total": 20
  },
  {
    "slug": "2011",
    "titulo": "ranking [2011]",
    "pagina": "ranking-2011.html",
    "imagem": "img/rankings/ranking-2011.png",
    "total": 15
  },
  {
    "slug": "2012",
    "titulo": "ranking [2012]",
    "pagina": "ranking-2012.html",
    "imagem": "img/rankings/ranking-2012.png",
    "total": 15
  },
  {
    "slug": "t25m",
    "titulo": "ranking [T25M]",
    "pagina": "ranking-t25m.html",
    "imagem": "img/rankings/ranking-t25m.png",
    "total": 25
  },
  {
    "slug": "t20f",
    "titulo": "ranking [T20F]",
    "pagina": "ranking-t20f.html",
    "imagem": "img/rankings/ranking-t20f.png",
    "total": 20
  }
];

const rankings = [
  {
    "rankingSlug": "2006",
    "posicao": "#1",
    "ordem": 1,
    "nome": "Enrico Borio",
    "categoria": "Ala",
    "time": "Jacksonville (EUA / DI)",
    "bio1": "Ala | Jacksonville (EUA / DI)",
    "bio2": "1.96m | 6'5 | 17/01/2006",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2006",
    "posicao": "#2",
    "ordem": 2,
    "nome": "Gustavo Guimarães",
    "categoria": "Pivô",
    "time": "Bradley (EUA / DI)",
    "bio1": "Pivô | Bradley (EUA / DI)",
    "bio2": "2.11m | 6'11 | 31/03/2006",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2006",
    "posicao": "#3",
    "ordem": 3,
    "nome": "Gabriel Ferreira \"Gigante\"",
    "categoria": "Pivô",
    "time": "Radford (EUA / DI)",
    "bio1": "Pivô | Radford (EUA / DI)",
    "bio2": "2.07m | 6'9 | 11/02/2006",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2006",
    "posicao": "#4",
    "ordem": 4,
    "nome": "Isaque Duarte",
    "categoria": "Pivô",
    "time": "São José",
    "bio1": "Pivô | São José",
    "bio2": "2.07m | 6'9 | 17/08/2006",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2006",
    "posicao": "#5",
    "ordem": 5,
    "nome": "Thaylor Gabriel",
    "categoria": "Armador",
    "time": "Joaçaba",
    "bio1": "Armador | Joaçaba",
    "bio2": "1.90m | 6'2 | 03/04/2006",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2006",
    "posicao": "#6",
    "ordem": 6,
    "nome": "Vinicius Santos",
    "categoria": "Ala",
    "time": "SESI Franca",
    "bio1": "Ala | SESI Franca",
    "bio2": "1.87m | 6'1 | 28/05/2006",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2006",
    "posicao": "#7",
    "ordem": 7,
    "nome": "Vitor Meili",
    "categoria": "Lateral",
    "time": "Pinheiros",
    "bio1": "Lateral | Pinheiros",
    "bio2": "1.84m | 6'1 | 24/09/2006",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2006",
    "posicao": "#8",
    "ordem": 8,
    "nome": "Luiz Guilherme",
    "categoria": "Lateral",
    "time": "Paulistano",
    "bio1": "Lateral | Paulistano",
    "bio2": "1.92m | 6'3 | 06/09/2006",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2006",
    "posicao": "#9",
    "ordem": 9,
    "nome": "Jackson Junior",
    "categoria": "Armador",
    "time": "São José",
    "bio1": "Armador | São José",
    "bio2": "1.84m | 6'1 | 19/05/2006",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2006",
    "posicao": "#10",
    "ordem": 10,
    "nome": "Jonathan Moreira \"Jojo\"",
    "categoria": "Armador",
    "time": "São José",
    "bio1": "Armador | São José",
    "bio2": "1.85m | 6'1 | 28/06/2006",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2006",
    "posicao": "#11",
    "ordem": 11,
    "nome": "Murilo Kuehne",
    "categoria": "Armador",
    "time": "Minas",
    "bio1": "Armador | Minas",
    "bio2": "1.85m | 6'1 | 28/06/2006",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2006",
    "posicao": "#12",
    "ordem": 12,
    "nome": "Gabriel Joaquim",
    "categoria": "Ala",
    "time": "Paulistano",
    "bio1": "Ala | Paulistano",
    "bio2": "2.01m | 6'7 | 20/06/2006",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2006",
    "posicao": "#13",
    "ordem": 13,
    "nome": "Yan Marun",
    "categoria": "Escolta",
    "time": "Flamengo",
    "bio1": "Escolta | Flamengo",
    "bio2": "1.85m | 6'1 | 31/07/2006",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2006",
    "posicao": "#14",
    "ordem": 14,
    "nome": "Antônio Silva \"Tonhão\"",
    "categoria": "Ala",
    "time": "Minas",
    "bio1": "Ala | Minas",
    "bio2": "1.91m | 6'3 | 28/09/2006",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2006",
    "posicao": "#15",
    "ordem": 15,
    "nome": "Luís Eduardo \"Baduzinho\"",
    "categoria": "Pivô",
    "time": "São José",
    "bio1": "Pivô | São José",
    "bio2": "2.00m | 6'6 | 21/12/2006",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#1",
    "ordem": 1,
    "nome": "Pedro Pastre",
    "categoria": "Ala",
    "time": "Pinheiros",
    "bio1": "Ala | Pinheiros",
    "bio2": "1.97m | 6'5 | 08/04/2007",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#2",
    "ordem": 2,
    "nome": "Patrick Otey",
    "categoria": "Lateral",
    "time": "St Thomas More (EUA / HS)",
    "bio1": "Lateral | St Thomas More (EUA / HS)",
    "bio2": "1.93m | 6'3 | 17/10/2007",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#3",
    "ordem": 3,
    "nome": "Junior Kemm",
    "categoria": "Escolta",
    "time": "SoCal Prep (EUA / HS)",
    "bio1": "Escolta | SoCal Prep (EUA / HS)",
    "bio2": "1.95m | 6'4 | 30/06/2007",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#4",
    "ordem": 4,
    "nome": "Augusto Toledo",
    "categoria": "Ala",
    "time": "SE Oklahoma St. (EUA / DII)",
    "bio1": "Ala | SE Oklahoma St. (EUA / DII)",
    "bio2": "1.98m | 6'6 | 06/05/2007",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#5",
    "ordem": 5,
    "nome": "Pedro Baddini",
    "categoria": "Armador",
    "time": "Obradoiro (ESP)",
    "bio1": "Armador | Obradoiro (ESP)",
    "bio2": "1.84m | 6'1 | 10/08/2007",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#6",
    "ordem": 6,
    "nome": "Matheus Monteiro \"Jamelão\"",
    "categoria": "Armador",
    "time": "Corinthians",
    "bio1": "Armador | Corinthians",
    "bio2": "1.78m | 5'10 | 12/04/2007",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#7",
    "ordem": 7,
    "nome": "Lucca Boracina",
    "categoria": "Armador",
    "time": "Pinheiros",
    "bio1": "Armador | Pinheiros",
    "bio2": "1.83m | 6'0 | 10/07/2007",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#8",
    "ordem": 8,
    "nome": "Carmelo Beloni",
    "categoria": "Ala",
    "time": "Pinheiros",
    "bio1": "Ala | Pinheiros",
    "bio2": "2.10m | 6'11 | 23/07/2007",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#9",
    "ordem": 9,
    "nome": "João Gomes",
    "categoria": "Ala",
    "time": "Orange1 (ITA)",
    "bio1": "Ala | Orange1 (ITA)",
    "bio2": "1.97m | 6'5 | 22/11/2007",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#10",
    "ordem": 10,
    "nome": "Vinci Oliveira",
    "categoria": "Grande",
    "time": "Minas",
    "bio1": "Grande | Minas",
    "bio2": "2.11m | 6'11 | 05/01/2007",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#11",
    "ordem": 11,
    "nome": "Hugo Nicolini",
    "categoria": "Lateral",
    "time": "SESI Franca",
    "bio1": "Lateral | SESI Franca",
    "bio2": "1.86m | 6'1 | 27/03/2007",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#12",
    "ordem": 12,
    "nome": "Lucas Milchevski",
    "categoria": "Ala",
    "time": "Flamengo",
    "bio1": "Ala  | Flamengo",
    "bio2": "2.02m | 6'7 | 22/02/2007",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#13",
    "ordem": 13,
    "nome": "Gabriel Vitoriano",
    "categoria": "Ala",
    "time": "Mogi",
    "bio1": "Ala | Mogi",
    "bio2": "2.00m | 6'6  | 29/07/2007",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#14",
    "ordem": 14,
    "nome": "Lucas Avanso",
    "categoria": "Ala",
    "time": "Paulistano",
    "bio1": "Ala | Paulistano",
    "bio2": "1.83m | 6'0 | 16/02/2007",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#15",
    "ordem": 15,
    "nome": "João Guimarães",
    "categoria": "Armador",
    "time": "São José",
    "bio1": "Armador | São José",
    "bio2": "1.90m | 6'2 | 30/04/2007",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#16",
    "ordem": 16,
    "nome": "Luiz Pereira",
    "categoria": "Grande",
    "time": "Paulistano",
    "bio1": "Grande | Paulistano",
    "bio2": "2.01m | 6'7 | 23/11/2007",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#17",
    "ordem": 17,
    "nome": "Bruno Rosseti",
    "categoria": "Lateral",
    "time": "Fluminense",
    "bio1": "Lateral | Fluminense",
    "bio2": "1.90m | 6'2 | 24/01/2007",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#18",
    "ordem": 18,
    "nome": "Wesley Gardolin",
    "categoria": "Ala",
    "time": "São Paulo",
    "bio1": "Ala | São Paulo",
    "bio2": "1.98m | 6'6 | 16/05/2007",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#19",
    "ordem": 19,
    "nome": "Wendell Vasconcelos",
    "categoria": "Escolta",
    "time": "São Paulo",
    "bio1": "Escolta | São Paulo",
    "bio2": "1.80m | 5'11 | 19/07/2007",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2007",
    "posicao": "#20",
    "ordem": 20,
    "nome": "Henrique Fernandes",
    "categoria": "Armador",
    "time": "Flamengo",
    "bio1": "Armador | Flamengo",
    "bio2": "1.78 | 5'10 | 15/01/2007",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#1",
    "ordem": 1,
    "nome": "Mathias Alessanco",
    "categoria": "Ala",
    "time": "RWE (EUA / HS)",
    "bio1": "Ala | RWE (EUA / HS)",
    "bio2": "2.06m | 6'9 | 26/03/2008",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#2",
    "ordem": 2,
    "nome": "Pedro Figueiredo",
    "categoria": "Armador",
    "time": "Baskonia (ESP)",
    "bio1": "Armador | Baskonia (ESP)",
    "bio2": "2.00m | 6'6 | 04/12/2008",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#3",
    "ordem": 3,
    "nome": "Isaiah Santos",
    "categoria": "Ala",
    "time": "Seven Lakes (EUA / HS)",
    "bio1": "Ala | Seven Lakes (EUA / HS)",
    "bio2": "1.96m | 6'5 | 10/11/2008",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#4",
    "ordem": 4,
    "nome": "João Gluck \"Pará\"",
    "categoria": "Ala",
    "time": "UCAM Murcia (ESP)",
    "bio1": "Ala | UCAM Murcia (ESP)",
    "bio2": "2.02m | 6'7 | 02/08/2008",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#5",
    "ordem": 5,
    "nome": "Pietro Melo",
    "categoria": "Armador",
    "time": "Paulistano",
    "bio1": "Armador | Paulistano",
    "bio2": "1.85m | 6'1 | 10/08/2008",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#6",
    "ordem": 6,
    "nome": "Francesco Borio",
    "categoria": "Ala",
    "time": "North Broward Prep (EUA / HS)",
    "bio1": "Ala | North Broward Prep (EUA / HS)",
    "bio2": "2.00m | 6'6 | 02/05/2008",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#7",
    "ordem": 7,
    "nome": "Thierry Henry",
    "categoria": "Grande",
    "time": "Baskonia (ESP)",
    "bio1": "Grande | Baskonia (ESP)",
    "bio2": "2.11m | 6'11 | 24/01/2008",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#8",
    "ordem": 8,
    "nome": "João Aragão",
    "categoria": "Ala",
    "time": "Paulistano",
    "bio1": "Ala | Paulistano",
    "bio2": "2.05m | 6'8 | 01/10/2008",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#9",
    "ordem": 9,
    "nome": "Bruno Solano",
    "categoria": "Ala",
    "time": "Zentro (ESP)",
    "bio1": "Ala | Zentro (ESP)",
    "bio2": "2.03m | 6'7 | 29/12/2008",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#10",
    "ordem": 10,
    "nome": "Matheus Nascimento",
    "categoria": "Armador",
    "time": "Pinheiros",
    "bio1": "Armador | Pinheiros",
    "bio2": "1.90m | 6'2 | 24/03/2008",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#11",
    "ordem": 11,
    "nome": "João Alves \"Hashi\"",
    "categoria": "Ala",
    "time": "Paulistano",
    "bio1": "Ala | Paulistano",
    "bio2": "1.99m | 6'6 | 05/08/2008",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#12",
    "ordem": 12,
    "nome": "Pierson Dejneka",
    "categoria": "Lateral",
    "time": "Huntington (EUA / HS)",
    "bio1": "Lateral | Huntington (EUA / HS)",
    "bio2": "1.91m | 6'3 | 22/09/2008",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#13",
    "ordem": 13,
    "nome": "Cristian Ferreira",
    "categoria": "Ala",
    "time": "Paulistano",
    "bio1": "Ala | Paulistano",
    "bio2": "1.96m | 6'5 | 26/08/2008",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#14",
    "ordem": 14,
    "nome": "Caio Mathias",
    "categoria": "Lateral",
    "time": "Paulistano",
    "bio1": "Lateral | Paulistano",
    "bio2": "1.86m | 6'1 | 05/08/2008",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#15",
    "ordem": 15,
    "nome": "Michael Pereira",
    "categoria": "Grande",
    "time": "Plymouth Whitemarsh (EUA / HS)",
    "bio1": "Grande | Plymouth Whitemarsh (EUA / HS)",
    "bio2": "2.08m | 6'10 | 04/12/2008",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#16",
    "ordem": 16,
    "nome": "Matheus Gabriel \"Mumuzinho\"",
    "categoria": "Grande",
    "time": "Fluminense",
    "bio1": "Grande | Fluminense",
    "bio2": "2.00m | 6'6 | 14/05/2008",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#17",
    "ordem": 17,
    "nome": "José Martins",
    "categoria": "Armador",
    "time": "Seven Lakes (EUA / HS)",
    "bio1": "Armador | Seven Lakes (EUA / HS)",
    "bio2": "1.93m | 6'3 | 08/04/2008",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#18",
    "ordem": 18,
    "nome": "Pedro Alves",
    "categoria": "Grande",
    "time": "Paulistano",
    "bio1": "Grande | Paulistano",
    "bio2": "2.06m | 6'9 | 24/04/2008",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#19",
    "ordem": 19,
    "nome": "Guga Machado",
    "categoria": "Armador",
    "time": "The Academy of Central Florida (EUA / HS)",
    "bio1": "Armador | The Academy of Central Florida (EUA / HS)",
    "bio2": "1.87m | 6'1 | 02/09/2008",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2008",
    "posicao": "#20",
    "ordem": 20,
    "nome": "Thomás Piemonte",
    "categoria": "Ala",
    "time": "IMG Academy (EUA)",
    "bio1": "Ala | IMG Academy (EUA)",
    "bio2": "2.05m | 6'8 | 20/12/2008",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#1",
    "ordem": 1,
    "nome": "Edu Santos",
    "categoria": "Ala",
    "time": "Pinheiros",
    "bio1": "Ala | Pinheiros",
    "bio2": "2.07m | 6'9 | 09/08/2009",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#2",
    "ordem": 2,
    "nome": "Lucas Thor Moro",
    "categoria": "Ala",
    "time": "PSAT Academy (EUA / HS)",
    "bio1": "Ala | PSAT Academy (EUA / HS)",
    "bio2": "1.99m | 6'6 | 17/04/2009",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#3",
    "ordem": 3,
    "nome": "Fernando Varallo",
    "categoria": "Grande",
    "time": "Pinheiros",
    "bio1": "Grande | Pinheiros",
    "bio2": "2.01m | 6'7 | 10/05/2009",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#4",
    "ordem": 4,
    "nome": "Vithor Dornelles",
    "categoria": "Escolta",
    "time": "SESI Franca",
    "bio1": "Escolta | SESI Franca",
    "bio2": "1.83m | 6'1 | 23/08/2009",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#5",
    "ordem": 5,
    "nome": "Matheus Mellim",
    "categoria": "Armador",
    "time": "SESI Franca",
    "bio1": "Armador | SESI Franca",
    "bio2": "1.72m | 5'7 | 25/06/2009",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#6",
    "ordem": 6,
    "nome": "Ruan Fernandes",
    "categoria": "Grande",
    "time": "CBA Badajoz (ESP)",
    "bio1": "Grande | CBA Badajoz (ESP)",
    "bio2": "2.09m | 6'10 | 13/10/2009",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#7",
    "ordem": 7,
    "nome": "Matheus Megda",
    "categoria": "Grande",
    "time": "SESI Franca",
    "bio1": "Grande | SESI Franca",
    "bio2": "2.00m | 6'6 | 02/02/2009",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#8",
    "ordem": 8,
    "nome": "Henrique Rocha",
    "categoria": "Grande",
    "time": "PSAT Academy (EUA / HS)",
    "bio1": "Grande | PSAT Academy (EUA / HS)",
    "bio2": "1.97m | 6'5 | 23/06/2009",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#9",
    "ordem": 9,
    "nome": "Kaio Oliver",
    "categoria": "Grande",
    "time": "Estudiantes (ESP)",
    "bio1": "Grande | Estudiantes (ESP)",
    "bio2": "2.15m | 7'0 | 31/01/2009",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#10",
    "ordem": 10,
    "nome": "Mateus Chiebuka",
    "categoria": "Grande",
    "time": "West Oaks (EUA / HS)",
    "bio1": "Grande | West Oaks (EUA / HS)",
    "bio2": "2.10m | 6'10 | 22/04/2009",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#11",
    "ordem": 11,
    "nome": "Natan Nascimento",
    "categoria": "Grande",
    "time": "Pinheiros",
    "bio1": "Grande | Pinheiros",
    "bio2": "1.97m | 6'5 | 24/07/2009",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#12",
    "ordem": 12,
    "nome": "Marcos Paulo Roger",
    "categoria": "Ala",
    "time": "Paulistano",
    "bio1": "Ala | Paulistano",
    "bio2": "1.95m | 6'4 | 26/10/2009",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#13",
    "ordem": 13,
    "nome": "Enzo Moreira",
    "categoria": "Ala",
    "time": "Florida Coastal Prep (EUA / HS)",
    "bio1": "Ala | Florida Coastal Prep (EUA / HS)",
    "bio2": "1.97m | 6'6 | 08/04/2008",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#14",
    "ordem": 14,
    "nome": "Victor Chaves",
    "categoria": "Lateral",
    "time": "Pinheiros",
    "bio1": "Lateral | Pinheiros",
    "bio2": "1.86m | 6'1 | 12/03/2009",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#15",
    "ordem": 15,
    "nome": "Victor Santos",
    "categoria": "Lateral",
    "time": "Paulistano",
    "bio1": "Lateral | Paulistano",
    "bio2": "1.96m | 6'5 | 08/07/2009",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#16",
    "ordem": 16,
    "nome": "Luigi Borio",
    "categoria": "Grande",
    "time": "North Broward Prep (EUA / HS)",
    "bio1": "Grande | North Broward Prep (EUA / HS)",
    "bio2": "1.97m | 6'6 | 24/07/2009",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#17",
    "ordem": 17,
    "nome": "Djavan Lima",
    "categoria": "Ala",
    "time": "Minas",
    "bio1": "Ala | Minas",
    "bio2": "1.91m | 6'3 | 09/10/2009",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#18",
    "ordem": 18,
    "nome": "Arthur Prado \"Tubarão\"",
    "categoria": "Lateral",
    "time": "SESI Franca",
    "bio1": "Lateral | SESI Franca",
    "bio2": "1.84m | 6'1 | 14/08/2009",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#19",
    "ordem": 19,
    "nome": "Bruno Bonatti",
    "categoria": "Armador",
    "time": "Pinheiros",
    "bio1": "Armador | Pinheiros",
    "bio2": "1.90m | 6'2 | 23/05/2009",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2009",
    "posicao": "#20",
    "ordem": 20,
    "nome": "Samuel Lúcio",
    "categoria": "Ala",
    "time": "Corinthians",
    "bio1": "Ala | Corinthians",
    "bio2": "1.93m | 6'3 | 01/09/2009",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#1",
    "ordem": 1,
    "nome": "Bernardo Jerônimo",
    "categoria": "Armador",
    "time": "St. Joseph (EUA / HS)",
    "bio1": "Armador | St. Joseph (EUA / HS)",
    "bio2": "1.92m | 6'3 | 23/08/2010",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#2",
    "ordem": 2,
    "nome": "Vinicius Ciribelli \"Big\"",
    "categoria": "Grande",
    "time": "Pinheiros",
    "bio1": "Grande | Pinheiros",
    "bio2": "2.02m | 6'7 | 16/04/2010",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#3",
    "ordem": 3,
    "nome": "Gabriel Romualdo",
    "categoria": "Escolta",
    "time": "Pinheiros",
    "bio1": "Escolta | Pinheiros",
    "bio2": "1.85m | 6'1 | 15/02/2010",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#4",
    "ordem": 4,
    "nome": "Matheus Michelini",
    "categoria": "Armador",
    "time": "Bauru",
    "bio1": "Armador | Bauru",
    "bio2": "1.80m | 5'10 | 26/07/2010",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#5",
    "ordem": 5,
    "nome": "Guilherme Coelho",
    "categoria": "Grande",
    "time": "Regatas",
    "bio1": "Grande | Regatas",
    "bio2": "1.96m | 6'5 | 26/01/2010",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#6",
    "ordem": 6,
    "nome": "Julio Penha",
    "categoria": "Ala",
    "time": "Paulistano",
    "bio1": "Ala | Paulistano",
    "bio2": "1.90m | 6'2 | 27/05/2010",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#7",
    "ordem": 7,
    "nome": "Rafael Rebelo",
    "categoria": "Ala",
    "time": "Pinheiros",
    "bio1": "Ala | Pinheiros",
    "bio2": "1.96m | 6'5 | 30/03/2010",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#8",
    "ordem": 8,
    "nome": "Gabriel Máximo",
    "categoria": "Armador",
    "time": "Minas",
    "bio1": "Armador | Minas",
    "bio2": "1.85m | 6'1 | 20/08/2010",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#9",
    "ordem": 9,
    "nome": "Ruan Kennedy",
    "categoria": "Armador",
    "time": "Dream City (EUA / HS)",
    "bio1": "Armador | Dream City (EUA / HS)",
    "bio2": "1.95m | 6'4 | 05/08/2010",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#10",
    "ordem": 10,
    "nome": "Renan Loureiro",
    "categoria": "Armador",
    "time": "Corinthians",
    "bio1": "Armador | Corinthians",
    "bio2": "1.83m | 6'0 | 28/02/2010",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#11",
    "ordem": 11,
    "nome": "Marco Quintino",
    "categoria": "Lateral",
    "time": "Regatas",
    "bio1": "Lateral | Regatas",
    "bio2": "1.91m | 6'2 | 04/10/2010",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#12",
    "ordem": 12,
    "nome": "Nicolas Prestes",
    "categoria": "Grande",
    "time": "DLang (SUI)",
    "bio1": "Grande | DLang (SUI)",
    "bio2": "2.03m | 6'7 | 14/10/2010",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#13",
    "ordem": 13,
    "nome": "Pedro Bressani",
    "categoria": "Ala",
    "time": "Pinheiros",
    "bio1": "Ala | Pinheiros",
    "bio2": "1.90m | 6'2 | 06/08/2010",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#14",
    "ordem": 14,
    "nome": "Hassan Brusamarello",
    "categoria": "Grande",
    "time": "Olimpia Milano (ITA)",
    "bio1": "Grande | Olimpia Milano (ITA)",
    "bio2": "2.05m | 6'8 | 21/08/2010",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#15",
    "ordem": 15,
    "nome": "Lucca Roppa",
    "categoria": "Armador",
    "time": "Foundation Academy (EUA / HS)",
    "bio1": "Armador | Foundation Academy (EUA / HS)",
    "bio2": "1.90m | 6'2 | 04/11/2010",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#16",
    "ordem": 16,
    "nome": "Davi Padovani",
    "categoria": "Armador",
    "time": "San Pablo Burgos (ESP)",
    "bio1": "Armador | San Pablo Burgos (ESP)",
    "bio2": "1.83m | 6'1 | 17/02/2010",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#17",
    "ordem": 17,
    "nome": "Andrew dos Santos",
    "categoria": "Armador",
    "time": "Paulistano",
    "bio1": "Armador | Paulistano",
    "bio2": "1.85m | 6'1 | 28/01/2010",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#18",
    "ordem": 18,
    "nome": "Michel Rebonato",
    "categoria": "Ala",
    "time": "Paulistano",
    "bio1": "Ala | Paulistano",
    "bio2": "1.98m | 6'6 | 16/04/2010",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#19",
    "ordem": 19,
    "nome": "Caio Leopoldo",
    "categoria": "Lateral",
    "time": "Mater Lakes (EUA / HS)",
    "bio1": "Lateral | Mater Lakes (EUA / HS)",
    "bio2": "1.98m | 6'6 | 28/02/2010",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2010",
    "posicao": "#20",
    "ordem": 20,
    "nome": "Ricardo Dalla",
    "categoria": "Ala",
    "time": "Estudiantes (ESP)",
    "bio1": "Ala | Estudiantes (ESP)",
    "bio2": "1.93m | 6'3 | 03/11/2010",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2011",
    "posicao": "#1",
    "ordem": 1,
    "nome": "Matteus Tesch",
    "categoria": "Lateral",
    "time": "Highlands Christian (EUA / HS)",
    "bio1": "Lateral | Highlands Christian (EUA / HS)",
    "bio2": "1.96m | 6'5 | 01/03/2011",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2011",
    "posicao": "#2",
    "ordem": 2,
    "nome": "Brenno Harnbaker",
    "categoria": "Armador",
    "time": "Pinheiros",
    "bio1": "Armador | Pinheiros",
    "bio2": "1.78m | 5'10 | 25/02/2011",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2011",
    "posicao": "#3",
    "ordem": 3,
    "nome": "Guilherme Alessanco",
    "categoria": "Armador",
    "time": "Corinthians",
    "bio1": "Armador | Corinthians",
    "bio2": "1.93m | 6'4 | 23/07/2011",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "2011",
    "posicao": "#4",
    "ordem": 4,
    "nome": "Heitor Toniolo",
    "categoria": "Ala",
    "time": "Highlands Christian (EUA / HS)",
    "bio1": "Ala | Highlands Christian (EUA / HS)",
    "bio2": "2.03m | 6'8 | 10/03/2011",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2011",
    "posicao": "#5",
    "ordem": 5,
    "nome": "Samuel Brasil",
    "categoria": "Armador",
    "time": "UCAM Murcia (ESP)",
    "bio1": "Armador | UCAM Murcia (ESP)",
    "bio2": "1.84m | 6'1 | 29/01/2011",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2011",
    "posicao": "#6",
    "ordem": 6,
    "nome": "Pryce Dejneka",
    "categoria": "Armador",
    "time": "DT ELITE (AAU)",
    "bio1": "Armador | DT ELITE (AAU)",
    "bio2": "1.78m | 5'10 | 07/10/2011",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2011",
    "posicao": "#7",
    "ordem": 7,
    "nome": "Enrico Boracina",
    "categoria": "Armador",
    "time": "Pinheiros",
    "bio1": "Armador | Pinheiros",
    "bio2": "1.78m | 5'10 | 18/04/2011",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2011",
    "posicao": "#8",
    "ordem": 8,
    "nome": "Raul Mendonça",
    "categoria": "Grande",
    "time": "N/A",
    "bio1": "Grande | N/A",
    "bio2": "2.03m | 6'8 | 24/01/2011",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2011",
    "posicao": "#9",
    "ordem": 9,
    "nome": "Pedro Batista",
    "categoria": "Grande",
    "time": "Pinheiros",
    "bio1": "Grande | Pinheiros",
    "bio2": "1.95m | 6'5 | 18/04/2011",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2011",
    "posicao": "#10",
    "ordem": 10,
    "nome": "Rafael Silva",
    "categoria": "Grande",
    "time": "Regatas",
    "bio1": "Grande | Regatas",
    "bio2": "1.95m | 6'5 | 10/07/2011",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2011",
    "posicao": "#11",
    "ordem": 11,
    "nome": "Gustavo Stankevicius",
    "categoria": "Grande",
    "time": "Pinheiros",
    "bio1": "Grande | Pinheiros",
    "bio2": "1.98m | 6'5 | 12/01/2011",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "2011",
    "posicao": "#12",
    "ordem": 12,
    "nome": "Sebas Tejas Rubio",
    "categoria": "Lateral",
    "time": "Zentro (ESP)",
    "bio1": "Lateral | Zentro (ESP)",
    "bio2": "1.87m | 6'1 | 16/01/2011",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2011",
    "posicao": "#13",
    "ordem": 13,
    "nome": "Gabriel Lourenço",
    "categoria": "Ala",
    "time": "Olympico",
    "bio1": "Ala | Olympico",
    "bio2": "1.88m | 6'2 | 10/01/2011",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2011",
    "posicao": "#14",
    "ordem": 14,
    "nome": "Breno Belkiman",
    "categoria": "Ala",
    "time": "Pinheiros",
    "bio1": "Ala | Pinheiros",
    "bio2": "1.90m | 6'2 | 14/05/2011",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2011",
    "posicao": "#15",
    "ordem": 15,
    "nome": "Igor Valverde",
    "categoria": "Armador",
    "time": "Santo André",
    "bio1": "Armador | Santo André",
    "bio2": "1.78m | 5'10 | 18/08/2011",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "2012",
    "posicao": "#1",
    "ordem": 1,
    "nome": "Emanoel de Paula",
    "categoria": "Grande",
    "time": "Pinheiros",
    "bio1": "Grande | Pinheiros",
    "bio2": "1.92m | 6'3 | 02/03/2012",
    "estrelas": ""
  },
  {
    "rankingSlug": "2012",
    "posicao": "#2",
    "ordem": 2,
    "nome": "Davih Alves",
    "categoria": "Lateral",
    "time": "Tijuca",
    "bio1": "Lateral | Tijuca",
    "bio2": "1.91m | 6'1 | 13/07/2012",
    "estrelas": ""
  },
  {
    "rankingSlug": "2012",
    "posicao": "#3",
    "ordem": 3,
    "nome": "Enzo Berton",
    "categoria": "Grande",
    "time": "Bauru",
    "bio1": "Grande | Bauru",
    "bio2": "1.95m | 6'5 | 02/01/2012",
    "estrelas": ""
  },
  {
    "rankingSlug": "2012",
    "posicao": "#4",
    "ordem": 4,
    "nome": "Bernardo Bochio",
    "categoria": "Armador",
    "time": "Mogi",
    "bio1": "Armador | Mogi",
    "bio2": "1.76m | 5'9 | 10/04/2012",
    "estrelas": ""
  },
  {
    "rankingSlug": "2012",
    "posicao": "#5",
    "ordem": 5,
    "nome": "Vinicius Vidal",
    "categoria": "Escolta",
    "time": "Mogi",
    "bio1": "Escolta | Mogi",
    "bio2": "1.74m | 5'8 | 09/06/2012",
    "estrelas": ""
  },
  {
    "rankingSlug": "2012",
    "posicao": "#6",
    "ordem": 6,
    "nome": "Daniel Klausing",
    "categoria": "Grande",
    "time": "Minas",
    "bio1": "Grande | Minas",
    "bio2": "1.94m | 6'5 | 08/10/2012",
    "estrelas": ""
  },
  {
    "rankingSlug": "2012",
    "posicao": "#7",
    "ordem": 7,
    "nome": "Caio Coelho",
    "categoria": "Ala",
    "time": "Tijuca",
    "bio1": "Ala | Tijuca",
    "bio2": "1.80m | 5'10 | 20/01/2012",
    "estrelas": ""
  },
  {
    "rankingSlug": "2012",
    "posicao": "#8",
    "ordem": 8,
    "nome": "Igor Willian",
    "categoria": "Ala",
    "time": "Mogi",
    "bio1": "Ala | Mogi",
    "bio2": "1.78m | 5'10 | 29/02/2012",
    "estrelas": ""
  },
  {
    "rankingSlug": "2012",
    "posicao": "#9",
    "ordem": 9,
    "nome": "Tiago Landeira",
    "categoria": "Armador",
    "time": "Tijuca",
    "bio1": "Armador | Tijuca",
    "bio2": "1.77m | 5'9 | 29/02/2012",
    "estrelas": ""
  },
  {
    "rankingSlug": "2012",
    "posicao": "#10",
    "ordem": 10,
    "nome": "Nicolas Fragg",
    "categoria": "Grande",
    "time": "Corinthians",
    "bio1": "Grande | Corinthians",
    "bio2": "10/02/2012",
    "estrelas": ""
  },
  {
    "rankingSlug": "2012",
    "posicao": "#11",
    "ordem": 11,
    "nome": "Fernando Pimentel",
    "categoria": "Lateral",
    "time": "Pinheiros",
    "bio1": "Lateral | Pinheiros",
    "bio2": "03/01/2012",
    "estrelas": ""
  },
  {
    "rankingSlug": "2012",
    "posicao": "#12",
    "ordem": 12,
    "nome": "Alef Daniel",
    "categoria": "Grande",
    "time": "Pinheiros",
    "bio1": "Grande | Pinheiros",
    "bio2": "2.01m | 6'7 | 28/09/2012",
    "estrelas": ""
  },
  {
    "rankingSlug": "2012",
    "posicao": "#13",
    "ordem": 13,
    "nome": "Gui Assis",
    "categoria": "Ala",
    "time": "Votorantim",
    "bio1": "Ala | Votorantim",
    "bio2": "1.89m | 6'2 | 17/03/2012",
    "estrelas": ""
  },
  {
    "rankingSlug": "2012",
    "posicao": "#14",
    "ordem": 14,
    "nome": "Ricardo Bueno",
    "categoria": "Lateral",
    "time": "Corinthians",
    "bio1": "Lateral | Corinthians",
    "bio2": "1.80m | 5'10 | 06/07/2012",
    "estrelas": ""
  },
  {
    "rankingSlug": "2012",
    "posicao": "#15",
    "ordem": 15,
    "nome": "Nicolas Vitorino",
    "categoria": "Armador",
    "time": "São José",
    "bio1": "Armador | São José",
    "bio2": "1.82m | 5'10 | 19/04/2012",
    "estrelas": ""
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#1",
    "ordem": 1,
    "nome": "Mathias Alessanco",
    "categoria": "Ala",
    "time": "RWE (EUA / HS)",
    "bio1": "Ala | RWE (EUA / HS)",
    "bio2": "2.06m | 6'9 | 26/03/2008",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#2",
    "ordem": 2,
    "nome": "Edu Santos",
    "categoria": "Ala",
    "time": "Pinheiros",
    "bio1": "Ala | Pinheiros",
    "bio2": "2.07m | 6'9 | 09/08/2009",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#3",
    "ordem": 3,
    "nome": "Pedro Figueiredo",
    "categoria": "Armador",
    "time": "Baskonia (ESP)",
    "bio1": "Armador | Baskonia (ESP)",
    "bio2": "2.00m | 6'6 | 04/12/2008",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#4",
    "ordem": 4,
    "nome": "João Gluck \"Pará\"",
    "categoria": "Ala",
    "time": "UCAM Murcia (ESP)",
    "bio1": "Ala | UCAM Murcia (ESP)",
    "bio2": "2.02m | 6'7 | 02/08/2008",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#5",
    "ordem": 5,
    "nome": "Pedro Pastre",
    "categoria": "Ala",
    "time": "Pinheiros",
    "bio1": "Ala | Pinheiros",
    "bio2": "1.97m | 6'5 | 08/04/2007",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#6",
    "ordem": 6,
    "nome": "Ruan Kennedy",
    "categoria": "Armador",
    "time": "Dream City (EUA / HS)",
    "bio1": "Armador | Dream City (EUA / HS)",
    "bio2": "1.95m | 6'4 | 05/08/2010",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#7",
    "ordem": 7,
    "nome": "Patrick Otey",
    "categoria": "Lateral",
    "time": "St Thomas More (EUA / HS)",
    "bio1": "Lateral | St Thomas More (EUA / HS)",
    "bio2": "1.93m | 6'3 | 17/10/2007",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#8",
    "ordem": 8,
    "nome": "Isaiah Santos",
    "categoria": "Ala",
    "time": "Seven Lakes (EUA / HS)",
    "bio1": "Ala | Seven Lakes (EUA / HS)",
    "bio2": "1.96m | 6'5 | 10/11/2008",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#9",
    "ordem": 9,
    "nome": "Junior Kemm",
    "categoria": "Escolta",
    "time": "SoCal Prep (EUA / HS)",
    "bio1": "Escolta | SoCal Prep (EUA / HS)",
    "bio2": "1.95m | 6'4 | 30/06/2007",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#10",
    "ordem": 10,
    "nome": "Bernardo Jerônimo",
    "categoria": "Armador",
    "time": "St. Joseph (EUA / HS)",
    "bio1": "Armador | St. Joseph (EUA / HS)",
    "bio2": "1.92m | 6'3 | 23/08/2010",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#11",
    "ordem": 11,
    "nome": "Caio Leopoldo",
    "categoria": "Lateral",
    "time": "Mater Lakes (EUA / HS)",
    "bio1": "Lateral | Mater Lakes (EUA / HS)",
    "bio2": "1.98m | 6'6 | 28/02/2010",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#12",
    "ordem": 12,
    "nome": "Lucas Thor Moro",
    "categoria": "Ala",
    "time": "PSAT Academy (EUA / HS)",
    "bio1": "Ala | PSAT Academy (EUA / HS)",
    "bio2": "1.99m | 6'6 | 17/04/2009",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#13",
    "ordem": 13,
    "nome": "Matteus Tesch",
    "categoria": "Lateral",
    "time": "Highlands Christian (EUA / HS)",
    "bio1": "Lateral | Highlands Christian (EUA / HS)",
    "bio2": "1.96m | 6'5 | 01/03/2011",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#14",
    "ordem": 14,
    "nome": "Brenno Harnbaker",
    "categoria": "Armador",
    "time": "Pinheiros",
    "bio1": "Armador | Pinheiros",
    "bio2": "1.78m | 5'10 | 25/02/2011",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#15",
    "ordem": 15,
    "nome": "Guilherme Alessanco",
    "categoria": "Armador",
    "time": "Corinthians",
    "bio1": "Armador | Corinthians",
    "bio2": "1.93m | 6'4 | 23/07/2011",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#16",
    "ordem": 16,
    "nome": "Hassan Brusamarello",
    "categoria": "Grande",
    "time": "Olimpia Milano (ITA)",
    "bio1": "Grande | Olimpia Milano (ITA)",
    "bio2": "2.05m | 6'8 | 21/08/2010",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#17",
    "ordem": 17,
    "nome": "Pietro Melo",
    "categoria": "Armador",
    "time": "Paulistano",
    "bio1": "Armador | Paulistano",
    "bio2": "1.85m | 6'1 | 10/08/2008",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#18",
    "ordem": 18,
    "nome": "Enrico Borio",
    "categoria": "Ala",
    "time": "Jacksonville (EUA / DI)",
    "bio1": "Ala | Jacksonville (EUA / DI)",
    "bio2": "1.96m | 6'5 | 17/01/2006",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#19",
    "ordem": 19,
    "nome": "Francesco Borio",
    "categoria": "Ala",
    "time": "North Broward Prep (EUA / HS)",
    "bio1": "Ala | North Broward Prep (EUA / HS)",
    "bio2": "2.00m | 6'6 | 02/05/2008",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#20",
    "ordem": 20,
    "nome": "Thierry Henry",
    "categoria": "Grande",
    "time": "Baskonia (ESP)",
    "bio1": "Grande | Baskonia (ESP)",
    "bio2": "2.11m | 6'11 | 24/01/2008",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#21",
    "ordem": 21,
    "nome": "Heitor Toniolo",
    "categoria": "Ala",
    "time": "Highlands Christian (EUA / HS)",
    "bio1": "Ala | Highlands Christian (EUA / HS)",
    "bio2": "2.03m | 6'8 | 10/03/2011",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#22",
    "ordem": 22,
    "nome": "Samuel Brasil",
    "categoria": "Armador",
    "time": "UCAM Murcia (ESP)",
    "bio1": "Armador | UCAM Murcia (ESP)",
    "bio2": "1.84m | 6'1 | 29/01/2011",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#23",
    "ordem": 23,
    "nome": "Pryce Dejneka",
    "categoria": "Armador",
    "time": "DT ELITE (AAU)",
    "bio1": "Armador | DT ELITE (AAU)",
    "bio2": "1.78m | 5'10 | 07/10/2011",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#24",
    "ordem": 24,
    "nome": "Enrico Boracina",
    "categoria": "Armador",
    "time": "Pinheiros",
    "bio1": "Armador | Pinheiros",
    "bio2": "1.78m | 5'10 | 18/04/2011",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "t25m",
    "posicao": "#25",
    "ordem": 25,
    "nome": "Raul Mendonça",
    "categoria": "Grande",
    "time": "N/A",
    "bio1": "Grande | N/A",
    "bio2": "2.03m | 6'8 | 24/01/2011",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#1",
    "ordem": 1,
    "nome": "Julia Preis",
    "categoria": "Grande",
    "time": "Santo André",
    "bio1": "Grande | Santo André",
    "bio2": "1.90m | 6'3 | 03/02/2009",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#2",
    "ordem": 2,
    "nome": "Manu Alves",
    "categoria": "Grande",
    "time": "Illinois (EUA / DI)",
    "bio1": "Grande | Illinois (EUA / DI)",
    "bio2": "1.90m | 6'2 | 02/01/2006",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#3",
    "ordem": 3,
    "nome": "Ayla McDowell",
    "categoria": "Lateral",
    "time": "South Carolina (EUA / DI)",
    "bio1": "Lateral | South Carolina (EUA / DI)",
    "bio2": "1.86m | 6'1 | 09/02/2007",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#4",
    "ordem": 4,
    "nome": "Ana Julia da Silva",
    "categoria": "Grande",
    "time": "São José",
    "bio1": "Grande | São José",
    "bio2": "1.93 | 6'4 | 18/06/2011",
    "estrelas": "★★★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#5",
    "ordem": 5,
    "nome": "Heloísa Carrera",
    "categoria": "Grande",
    "time": "Arizona St. (EUA / DI)",
    "bio1": "Grande | Arizona St. (EUA / DI)",
    "bio2": "1.88m | 6'2 | 17/04/2006",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#6",
    "ordem": 6,
    "nome": "Aaliyah Guyton",
    "categoria": "Armadora",
    "time": "Illinois (EUA / DI)",
    "bio1": "Armadora | Illinois (EUA / DI)",
    "bio2": "1.70m | 5'7 | 27/05/2006",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#7",
    "ordem": 7,
    "nome": "Micaela Cavalcanti",
    "categoria": "Armadora",
    "time": "DME (EUA /HS)",
    "bio1": "Armadora | DME (EUA /HS)",
    "bio2": "1.64m | 5'4 | 05/04/2008",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#8",
    "ordem": 8,
    "nome": "Ana Laura Barreto",
    "categoria": "Lateral",
    "time": "Foz",
    "bio1": "Lateral | Foz",
    "bio2": "1.73m | 5'8 | 14/02/2010",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#9",
    "ordem": 9,
    "nome": "Alexia Dagba",
    "categoria": "Ala",
    "time": "Georgetown (EUA / DI)",
    "bio1": "Ala | Georgetown (EUA / DI)",
    "bio2": "1.83m | 6'0 | 04/11/2006",
    "estrelas": "★★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#10",
    "ordem": 10,
    "nome": "Raissa Zanolla",
    "categoria": "Lateral",
    "time": "Badajoz (ESP)",
    "bio1": "Lateral | Badajoz (ESP)",
    "bio2": "1.79m | 5'10 | 15/07/2007",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#11",
    "ordem": 11,
    "nome": "Laura Lira",
    "categoria": "Grande",
    "time": "Nosso Clube Vitaliza",
    "bio1": "Grande | Nosso Clube Vitaliza",
    "bio2": "1.86m | 6'1 | 13/04/2011",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#12",
    "ordem": 12,
    "nome": "Sara Dagba",
    "categoria": "Ala",
    "time": "Central Pointe (EUA / HS)",
    "bio1": "Ala | Central Pointe (EUA / HS)",
    "bio2": "6'2 | 07/05/2008",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#13",
    "ordem": 13,
    "nome": "Giovanna Roberto",
    "categoria": "Grande",
    "time": "Apagebask",
    "bio1": "Grande | Apagebask",
    "bio2": "1.85m | 6'1 | 01/06/2011",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#14",
    "ordem": 14,
    "nome": "Yasmin Dias",
    "categoria": "Armadora",
    "time": "São José",
    "bio1": "Armadora | São José",
    "bio2": "1.70m | 5'7 | 18/02/2011",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#15",
    "ordem": 15,
    "nome": "Sther Ubaka",
    "categoria": "Ala",
    "time": "DME (EUA / HS)",
    "bio1": "Ala | DME (EUA / HS)",
    "bio2": "1.81m | 5'11 | 12/09/2007",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#16",
    "ordem": 16,
    "nome": "Sofia Moschen",
    "categoria": "Ala",
    "time": "Bowling Green (EUA / DI)",
    "bio1": "Ala | Bowling Green (EUA / DI)",
    "bio2": "1.80m | 5'10 | 13/03/2007",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#17",
    "ordem": 17,
    "nome": "Rebeca Soares",
    "categoria": "Grande",
    "time": "Mount Baker (EUA / HS)",
    "bio1": "Grande | Mount Baker (EUA / HS)",
    "bio2": "1.88m | 6'2 | 06/05/2008",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#18",
    "ordem": 18,
    "nome": "Laura Rosa",
    "categoria": "Ala",
    "time": "Thalia",
    "bio1": "Ala | Thalia",
    "bio2": "1.78m | 5'9 | 05/06/2010",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#19",
    "ordem": 19,
    "nome": "Eloah Vitoria",
    "categoria": "Armadora",
    "time": "Tupã",
    "bio1": "Armadora | Tupã",
    "bio2": "1.70m | 5'7 |12/02/2011",
    "estrelas": "★★★"
  },
  {
    "rankingSlug": "t20f",
    "posicao": "#20",
    "ordem": 20,
    "nome": "Sara Martins",
    "categoria": "Ala",
    "time": "São José",
    "bio1": "Ala | São José",
    "bio2": "1.80m | 5'10 | 03/09/2008",
    "estrelas": "★★★"
  }
];
